### ISSUE TITLE
Null Pointer Exception while importing .schem files to new object layer

### ISSUE THREAD

**Issue by KingSnailtan** [Captain-Chaos/WorldPainter#101]
How to reproduce:

Import .schem files into a new object Layer

Relevant Files are in the attachment
[TheExeptionMessage.txt](https://github.com/Captain-Chaos/WorldPainter/files/3114434/TheExeptionMessage.txt)
[logfile0.txt](https://github.com/Captain-Chaos/WorldPainter/files/3114435/logfile0.txt)

[SchemFiles.zip](https://github.com/Captain-Chaos/WorldPainter/files/3114433/SchemFiles.zip)

**Comment by Captain-Chaos** [comment]
Thanks for the excellent bug report! All this information allowed me to very quickly diagnose the issue.

**Comment by Captain-Chaos** [comment]
I'm not convinced those files are following the standard (they lack a name, for example), but nevertheless I've made the schem support more robust, and fixed a bug with the offsets (which could not be changed). The next release of the beta will be able to load and use these schems.

**Comment by Captain-Chaos** [comment]
The new version of the beta is released. It won't auto-update, but you can download it from the links in the reddit post. Let me know if you still have trouble or find additional issues!
