### ISSUE TITLE
won't let me access biomes viewer on Mac or windows 

### ISSUE THREAD

**Issue by RecoveryAwareness** [Captain-Chaos/WorldPainter#104]
won't let me access biomes viewer on Mac or windows  I have Minecraft installed on both systems and it won't let me access the biomes viewer

**Comment by Captain-Chaos** [comment]
It needs access to specific versions of Minecraft for that. Specifically, it doesn't support Minecraft 1.13 or later yet (and might never do). You can select older versions of Minecraft in the Minecraft launcher; if you add a configuration for version 1.12.2 and launch it once, WorldPainter will pick up that .jar and use it to show biomes. But only for Minecraft 1.12.2 and older.
