### ISSUE TITLE
[2.6.0.RC2] NPE while importing a new world from a MC map.

### ISSUE THREAD

**Issue by Yldales** [Captain-Chaos/WorldPainter#105]
Hi,

The following error appear while trying to import an existing 1.13.2 world into WorldPainter.

```
java.lang.NullPointerException: null
	at org.pepsoft.minecraft.MC113AnvilChunk.<init>(MC113AnvilChunk.java:57)
	at org.pepsoft.worldpainter.DefaultPlatformProvider.createChunk(DefaultPlatformProvider.java:49)
	at org.pepsoft.worldpainter.exporting.JavaChunkStore.lambda$visitChunks$3(JavaChunkStore.java:289)
	at org.pepsoft.worldpainter.exporting.JavaChunkStore.visitRegions(JavaChunkStore.java:273)
	at org.pepsoft.worldpainter.exporting.JavaChunkStore.visitChunks(JavaChunkStore.java:283)

WorldPainter version: 2.6.0.RC2 (20190428220559)

java.version: 1.8.0_191
java.vendor: Oracle Corporation
java.vm.version: 25.191-b12
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\Yldales
user.dir: C:\Program Files\WorldPainter
user.country: FR
user.language: fr

Free memory: 387973400 bytes
Total memory size: 1051721728 bytes
Max memory size: 5583142912 bytes

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]
```

**Comment by Yldales** [comment]
Using NBTExplorer to inspect the errored .mca file, I've found some chunks with no TAG_LIST Sections. Deleting thoses chunks allowed WorldPainter to successfully import the map (without to many losses).

**Comment by Captain-Chaos** [comment]
Thanks for reporting this error and doing the research! Apparently Minecraft will create chunks with no sections (which is odd, since those contain the block data, so those chunks will not have contained any blocks and were no loss). I'll add a check for that so it doesn't crash on these maps.

**Comment by Captain-Chaos** [comment]
Actually, what kind of map was this? I need to know whether the lack of sections means the chunk can be ignored, or if it means that it is a void chunk; a legitimate chunk completely filled with air.
