### ISSUE TITLE
Custom layer + frost layer issue on beta 1.13

### ISSUE THREAD

**Issue by Vincentlego** [Captain-Chaos/WorldPainter#108]
When painting a custom ground cover object layer (a 'snow block' cover digging 1 block into the ground) and the frost layer on the same place, the generated map completely ignore the frost layer, leaving only a bare snow block layer where the two layers merge together.

I hope that i'm clear with the issue oof

**Comment by Captain-Chaos** [comment]
Can you attach a .world file that demonstrates the issue?

**Comment by Vincentlego** [comment]
Here you go:
http://www.mediafire.com/file/frg3i9t24mq6yr4/Kaegord+1.13+SV11+-+Copie.world

**Comment by Captain-Chaos** [comment]
This should have been fixed in the mean time. Feel free to file another ticket if necessary.
