### ISSUE TITLE
MinecraftCoords class got removed?

### ISSUE THREAD

**Issue by Barteks2x** [Captain-Chaos/WorldPainter#109]
In build 30 of cubic chunks support plugin (https://github.com/OpenCubicChunks/WorldPainterSupportCC/releases) I use `MinecraftCoords` class, which is accessible in source, but doesn't appear to exist in the WorldPainter that can be downloaded at https://www.worldpainter.net/. The class also appears to still exist in the master branch.

The source I use in my IDE is (I think) latest commit from v2.5.2-fixes branch, and version 1.3.0-SNAPSHOT of PluginParent.

This is the error from WorlsPainter when trying to export:
```
java.lang.NoClassDefFoundError: org/pepsoft/minecraft/MinecraftCoords
	at io.github.opencubicchunks.worldpainterplugin.CubicChunkStore.lambda$chunksLazyInit$1(CubicChunkStore.java:73)
	at cubicchunks.regionlib.lib.Region.forEachKey(Region.java:158)
	at cubicchunks.regionlib.api.storage.SaveSection.lambda$forAllKeys$3(SaveSection.java:139)
	at cubicchunks.regionlib.lib.provider.SimpleRegionProvider.forAllRegions(SimpleRegionProvider.java:120)
	at cubicchunks.regionlib.lib.provider.SharedCachedRegionProvider.forAllRegions(SharedCachedRegionProvider.java:118)

Root cause:
java.lang.ClassNotFoundException: org.pepsoft.minecraft.MinecraftCoords
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.github.opencubicchunks.worldpainterplugin.CubicChunkStore.lambda$chunksLazyInit$1(CubicChunkStore.java:73)
	at cubicchunks.regionlib.lib.Region.forEachKey(Region.java:158)

WorldPainter version: 2.5.12 (20190317213827)

java.version: 1.8.0_212
java.vendor: IcedTea
java.vm.version: 25.212-b04
java.vm.vendor: IcedTea
java.vm.name: OpenJDK 64-Bit Server VM
os.name: Linux
os.arch: amd64
os.version: 5.1.0-gentoobisect
user.home: /home/bartosz
user.dir: /home/bartosz/worldpainter
user.country: PL
user.language: pl

Free memory: 255071520 bytes
Total memory size: 435159040 bytes
Max memory size: 3719299072 bytes

World name: Generated World
Seed: -8130492891524922327
Bounds: -2, -2 => 2, 2
Height: 256
Number of tiles: 25
Layers in use: 
Border: null @ 62
Sub surface material: Stone Mix
Water height: 62

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]
```

**Comment by Captain-Chaos** [comment]
Yeah that class is new and isn't in a production release yet. It does exist in the beta however, so that should be able to load the plugin: https://www.reddit.com/r/Worldpainter/comments/bg7dgb/minecraft_113_support_beta_released/

**Comment by Captain-Chaos** [comment]
In your IDE you're probably getting it from a snapshot dependency via PluginParent or something like that. It only exists on the master branch, not on the v2.5.2-fixes branch. But the next release of WorldPainter will be from master, so you should switch to that branch anyway.

**Comment by Barteks2x** [comment]
Oh, I didn't think it could be a new class. I will probably have to remove all it's uses anyway.

**Comment by Captain-Chaos** [comment]
I just released the new production version of WorldPainter. You should be using version 1.3.0 of PluginParent now (it's not yet in Maven Central, but should be shortly).
