### ISSUE TITLE
Generation

### ISSUE THREAD

**Issue by PalePyth** [Captain-Chaos/WorldPainter#11]
Is it possible to generate modded ores as well?

**Comment by Captain-Chaos** [comment]
Yes, just use a custom underground pockets layer and create a custom material with the right block ID. This isn't a channel for asking questions though, so in future please use a different method (official support thread on Minecraft forum: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1261257-worldpainter-v2-1-3-graphical-interactive-map, Facebook page: https://www.facebook.com/worldpainter, etc.).
