### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Thund3rst0rm89** [Captain-Chaos/WorldPainter#115]
Everywhere i click to open a new window like "select Custom Material" or "Save World", "Properties" or something else i only get a white screen.

![WP2 6_whitescreen](https://user-images.githubusercontent.com/41584155/58434522-6482a000-80bc-11e9-92a2-718ab8bc7d47.jpg)

Cannot click on Custom Layers +
Nothing happen

I cannot export a minecraft card because of the white Screen

**Comment by Captain-Chaos** [comment]
This is probably due to selecting a different hardware acceleration method. I would suggest to change it back, but I see the Preferences screen is one of the ones not working. Could you try deleting your config file (`%APPDATA%\WorldPainter\config`)?

**Comment by Thund3rst0rm89** [comment]
yes it works thanks for the really fast answer. No i can search right issues 👍

**Comment by Captain-Chaos** [comment]
Glad to hear it! I'll close this issue then.

Your export problem sounds like a new issue. Try the new release I just made (version 2.6.1); if it still does not work, please file a new issue!
