### ISSUE TITLE
Ice does not appear on the water 1.2-1.12

### ISSUE THREAD

**Issue by Leonex95** [Captain-Chaos/WorldPainter#120]
After the upgrade, the ice(frost) layer does not appear. He is not. But he begins to appear gradually.
It used to be that when applying a layer of ice(frost), when entering the game, ice appeared immediately and completely on the water

https://www.mediafire.com/file/gw4wybg9hhfi41z/test_frost.world/file

**Comment by Captain-Chaos** [comment]
Thanks for reporting this error! It's been fixed in version 2.6.2 which I just release. Let me know if you encounter any further problems!
