### ISSUE TITLE
Frost Layer 

### ISSUE THREAD

**Issue by Thund3rst0rm89** [Captain-Chaos/WorldPainter#124]
In version 1.12 the grass blocks changed when I used a frost layer. In the 1.13 they do not do that, they are still so green and do not change. I do not know if this is a mistake of yours or if Minecraft has changed something in the new version here. Nevertheless, I wanted to report it. In the picture you can see it in the red circles. And I have a question about the layers, why can not a frost layer, snow, be placed on deep snow? You can see that on the green circle. I would like to have a smooth snow landscape, but the grass blocks sometimes look through again and again. Can you help me if that is feasible?

Many Thanks

Translated with Google

![snow](https://user-images.githubusercontent.com/41584155/59162894-2db77b80-8af9-11e9-8e47-a5b4cf35c88e.jpg)

**Comment by Captain-Chaos** [comment]
The change in behaviour I think is a Minecraft bug. It now turns grass blocks underneath snow thicker than one single layer into dirt blocks (as if another solid block was put on top of them). In the past it would leave them as grass blocks. Grass blocks can have the snowy sides, but dirt blocks cannot.

**Comment by Captain-Chaos** [comment]
The snow not being placed on deep snow was a bug which has been fixed in the mean time.

**Comment by Captain-Chaos** [comment]
If you don't want tall grass poking through, use the Bare Grass terrain (which has no tall grass on it) instead of the Grass terrain. Also, in future, please don't report multiple issues in one ticket.
