### ISSUE TITLE
Crash when exporting a world that has been saved with 2.5.x? (I got the original issue wrong)

### ISSUE THREAD

**Issue by Barteks2x** [Captain-Chaos/WorldPainter#125]
~~With the update to 2.6.0 I renamed my plugin Platform name to include Minecraft version range.~~

After saving a world with older version, and loading it with newer one ~~, WorldPainter is looking for platform named `CubicChunks`  which doesn't exist anymore crashing with the following exception:~~ WorkdPainter crashes with this exception and Im still figuring out why:

```
java.lang.NullPointerException: null
	at org.pepsoft.worldpainter.plugins.PlatformManager.getDefaultExportDir(PlatformManager.java:50)
	at org.pepsoft.worldpainter.ExportWorldDialog.<init>(ExportWorldDialog.java:87)
	at org.pepsoft.worldpainter.App$47.performAction(App.java:6212)
	at org.pepsoft.worldpainter.util.BetterAction.actionPerformed(BetterAction.java:53)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	<awt and swing stuff>
```

~~Which I think points to 2 deeper deeper issues:~~
 * ~~the platform ID saved in the WP world is the same as the human readable string, for which there is no reason to disallow changing. It should have a separate registered ID.~~
 * ~~It appears to be impossible to change world platform after it has been created.~~

**Comment by Barteks2x** [comment]
Nevermind, I need to figure it out by myself. `Platform` class `toString` and the way debugger showed it made me think it was all strings involved when it was objects.

**Comment by Barteks2x** [comment]
Not an issue in WP. I got very confused and forgot I changed platform ID. After more debugging I found the real cause.

**Comment by Barteks2x** [comment]
But I think the issue of being unable to change the platform when loading world is still a valid one.

**Comment by Captain-Chaos** [comment]
Sorry I never got back to you. I've been hard at work and have had to neglect WorldPainter for a while. The whole platform/plugin mechanism is definitely clunky and ripe for much improvement.
