### ISSUE TITLE
Flowers on schematics in custom object layers being bugged

### ISSUE THREAD

**Issue by frogocomics** [Captain-Chaos/WorldPainter#14]
I have a schematic with flowers and they aren't being exported in an custom object layer. 

Settings:
Random rotation and mirroring
Spawn on solid land
Collide with solid blocks
Always replace underground blocks
Leaf blocks should not decay

**Comment by frogocomics** [comment]
Custom layer: http://www.mediafire.com/download/m3umi92m9g9bh8m/Bushes.layer

**Comment by Captain-Chaos** [comment]
Minecraft only allows flowers on dirt and grass blocks. I suspect that in your custom objects they aren't supported by dirt or grass, is that correct?

**Comment by frogocomics** [comment]
Right, is there a way for you to allow this?

Best Regards,
Jeff Chen

------
I am not responsible for sudden heart attacks.
------

**Comment by Captain-Chaos** [comment]
Yes, there is an advanced setting to turn off the post processing WorldPainter does to enforce those rules. See the second to last setting on this page: http://www.worldpainter.net/trac/wiki/AdvancedSettings
