### ISSUE TITLE
[Suggestion] Add Bamboo to the custom plants layer

### ISSUE THREAD

**Issue by MattiBorchers** [Captain-Chaos/WorldPainter#144]
Bamboos wer added in Minecraft 1.14 and should be available in the "custom plants layer". In Addition, it should rarely spawn in the "Jungle" layer, when exporting the map to 1.14 or newer.

Talking about new versions, beehives should also appear in the "Decidious" layer (when the update 1.15 is ready)

**Comment by Thund3rst0rm89** [comment]
yes that would be helpful. At this time @MattiBorchers you can make it with schematics and custom object layer, but it is really exhausting

**Comment by Captain-Chaos** [comment]
Bamboo is now in. Sorry for taking so long!
