### ISSUE TITLE
Custom "Frost" like layer/terrain

### ISSUE THREAD

**Issue by JibayMcs** [Captain-Chaos/WorldPainter#155]
Hi !

I'm working on WorldPainter for a long time ago, and thank you for this software !

But I try to make a "Frost" like terrain layer with custom modded layered blocks

In my case I've make some tests with layered stone.

But when I export the map, I've air blocks under most thin stone layer blocks

It's possible to have more details to correctly add this particular custom layers in the world ?

I've linked my .world and a screenshot of the "bug".

Thanks for any responses ! :)

[layered_stone.world](https://github.com/Captain-Chaos/WorldPainter/files/4414124/layered_stone.zip)

![2020-04-01_11 15 05](https://user-images.githubusercontent.com/7621593/78121002-20aea480-740b-11ea-9bda-914ca29f00a9.png)

**Comment by JibayMcs** [comment]
Fixed, forgot to use 8 layers instead of 1

**Comment by banjofanatic** [comment]
Hello! I've been wanting to do this for awhile. How did you figure it out? I'd like to make use of the many layer blocks in the Conquest Reforged mod using the Frost mechanic. Thank you!
