### ISSUE TITLE
[Question] How do you calculate slopes?

### ISSUE THREAD

**Issue by Masy** [Captain-Chaos/WorldPainter#16]
I'm trying to write a generator that sets blocks by the angle of the slope, but i can't seem to find it in the code. I mean the function where you can only operate over/under x degree. How exactly do you calculate the degree per block?

**Comment by frogocomics** [comment]
I haven't checked the code, but I assume it has to do with sampling the blocks beside it.

**Comment by Captain-Chaos** [comment]
Sorry for not getting back to you sooner!

Both org.pepsoft.worldpainter.Tile and -.Dimension have a getSlope(int x, int y) method, which you could either use, or look at to see how it's calculated. Basically it takes the highest of the slopes between the four pairs of straight and diagonal neighbouring blocks. Which means that it actually entirely disregards the height of the central block for which it's calculating the slope.
