### ISSUE TITLE
The paypal donation isn't working, 404 Not Found

### ISSUE THREAD

**Issue by Ant0ine64** [Captain-Chaos/WorldPainter#161]
When I want to make a donation by using Help>About>Donate, i get a 404 page not found

I think that this problem is located in the following file
`WorldPainter/WPGUI/src/main/java/org/pepsoft/worldpainter/AboutDialog.java` at line 157

By the way, this webpage that opens displays version information about the host server 
`Apache/2.4.18 (Ubuntu) Server at www.worldpainter.net Port 443`
In order to hide thoses, modify the `ServerTokens` to `Prod` in the following file `/etc/apache2/conf-enabled/security.conf` and then restart your apache2 service

**Comment by Captain-Chaos** [comment]
Thanks for letting me know; it's been fixed!
