### ISSUE TITLE
Custom material Layermode resets thickness

### ISSUE THREAD

**Issue by Ivainir** [Captain-Chaos/WorldPainter#17]
I've noticed for a while now that whenever I make a new custom material and select the "layers" option, the thickness of layers is somewhat buggy.
If I set the thickness of new material layers to anything other than 3, it scales them back down close to 3 upon opening the terrain again upon re-opening the material.
Each time I re-open it, it scales it further back, usually taking no more than 2 or sometimes 3 iterations to get completely back to all layers having a thickness of 3. 
This happens both in repeated layer mode and in single layer mode, regardless of further settings.

**Comment by Captain-Chaos** [comment]
Yes, someone else (or was it you?) reported that recently. I've found the bug and will fix it in the next release. Sorry about that!
