### ISSUE TITLE
Script file language js not supported

### ISSUE THREAD

**Issue by MattiBorchers** [Captain-Chaos/WorldPainter#188]
Hello,

I am tryping to run a selfmade script from the command line with the wpscript.exe and get the following error message:

![error](https://user-images.githubusercontent.com/47185281/100276090-40c64180-2f61-11eb-8eb1-b9d5e87d3944.png)

The cmd command looks like this:

"C:\Program Files\WorldPainter\wpscript.exe" "C:\Users\sterl\Desktop\Tiles\wpscript.js"

The following Java version is installed:

![java-version](https://user-images.githubusercontent.com/47185281/100276127-4de33080-2f61-11eb-92c9-1f1d1de4e27a.png)

**Comment by Crescentine** [comment]
can confirm issue does exist- am the one having it

**Comment by Captain-Chaos** [comment]
It looks like Oracle has, as they long threatened to do, stopped shipping the Nashorn JavaScript engine with Java. You should be able to install it manually though. And in fact you don't even have to use JavaScript; any JSR 223 implementation will do. You could use PHP for your scripts for example.

**Comment by Captain-Chaos** [comment]
I'll take a look at what the easiest way is to add JavaScript support back to your JVM.

**Comment by Captain-Chaos** [comment]
@MattiBorchers You seem to be using Java 8, which _should_ still include Nashorn, so I am surprised you are getting the error! How did you install Java? Could it be that Nashorn was somehow not installed, or removed? Do you have other Java versions installed on your system?

**Comment by Crescentine** [comment]
> It looks like Oracle has, as they long threatened to do, stopped shipping the Nashorn JavaScript engine with Java. You should be able to install it manually though. And in fact you don't even have to use JavaScript; any JSR 223 implementation will do. You could use PHP for your scripts for example.

Whats funny is i solved the error YESTERDAY! I managed to get it working by downgrading to JRE 14.

**Comment by Crescentine** [comment]
> @MattiBorchers You seem to be using Java 8, which _should_ still include Nashorn, so I am surprised you are getting the error! How did you install Java? Could it be that Nashorn was somehow not installed, or removed? Do you have other Java versions installed on your system?

I had JRE 15, downgraded to 14 which was on my other computer.

**Comment by Crescentine** [comment]
> @MattiBorchers You seem to be using Java 8, which _should_ still include Nashorn, so I am surprised you are getting the error! How did you install Java? Could it be that Nashorn was somehow not installed, or removed? Do you have other Java versions installed on your system?

On this topic, of worldpainter, without opening a new issue, do you know if its possible to swap region files and get it to still work for importing a map in world painter?

**Comment by Captain-Chaos** [comment]
Yes, downgrading Java is of course the easiest solution. 😉 Java 14 is no longer supported though, so I would go to Java 11 in that case, which is supported until September 2023.

I'm toying with the idea of dropping Java 8 support, but I will support Java 11 until that too is out of support, at least.

**Comment by MattiBorchers** [comment]
Now with Minecraft 1.17 using Java 16 it would be a good time to switch the Javascript engine (maybe GraalVM). WorldPainter itself runs perfect on Java 16, only the scripting engine makes problems.

**Comment by MattiBorchers** [comment]
> @Captain-Chaos  You could use PHP for your scripts for example.

How would I do that?
I tried this with a simple *.php file with only an echo but get the message:
`Script file language php not supported`
when trying to execute the script from the cmd.

[https://imgur.com/a/G4KfPup](https://imgur.com/a/G4KfPup)

The same goes for python.

**Comment by Captain-Chaos** [comment]
> Now with Minecraft 1.17 using Java 16 it would be a good time to switch the Javascript engine (maybe GraalVM). WorldPainter itself runs perfect on Java 16, only the scripting engine makes problems.

GraalVM is a Java VM, no? I did not think it included a JavaScript engine, although I'm not very familiar with it.

**Comment by Captain-Chaos** [comment]
@MattiBorchers WorldPainter does not include any scripting engine; it relies on Java's build in pluggable scripting engine framework, called JSR 223, which allows any scripting engine with JSR 223 support to be very simply installed into the JRE (usually by dropping it into the lib/jre directory of the JRE) making its language automatically be supported by WorldPainter.

Java used to include such a JSR 223 scripting engine for JavaScript, but annoyingly they have removed it so now there is no scripting support by default on newer versions of Java. Using Java 8 or 11 is a good option to get it back though. I may move WorldPainter to Java 11 in the near future, so that is probably the best bet.

Another option is to install a JSR 223 scripting engine yourself. The one that used to be included in Java (Nashorn) is still available as a stand alone library. I _think_ I've also seen a PHP engine with JSR 223 support. Don't know about Python, but there's a good chance that exists too. If you google any scripting language together with "jsr 223" you should be able to get somewhere.

I didn't know GraalVM also included a JavaScript engine. I may look into including it, or another engine, with WorldPainter, but as you probably have noticed I've had very little time to work on WorldPainter lately so I would not count on it any time soon!

**Comment by CaliberMC** [comment]
> @MattiBorchers WorldPainter does not include any scripting engine; it relies on Java's build in pluggable scripting engine framework, called JSR 223, which allows any scripting engine with JSR 223 support to be very simply installed into the JRE (usually by dropping it into the `lib/jre` directory of the JRE) making its language automatically be supported by WorldPainter.
> 
> Java used to include such a JSR 223 scripting engine for JavaScript, but annoyingly they have removed it so now there is no scripting support by default on newer versions of Java. Using Java 8 or 11 is a good option to get it back though. I may move WorldPainter to Java 11 in the near future, so that is probably the best bet.
> 
> Another option is to install a JSR 223 scripting engine yourself. The one that used to be included in Java (Nashorn) is still available as a stand alone library. I _think_ I've also seen a PHP engine with JSR 223 support. Don't know about Python, but there's a good chance that exists too. If you google any scripting language together with "jsr 223" you should be able to get somewhere.
> 
> I didn't know GraalVM also included a JavaScript engine. I may look into including it, or another engine, with WorldPainter, but as you probably have noticed I've had very little time to work on WorldPainter lately so I would not count on it any time soon! It looks like it also has JSR 223 support, so you could look into whether it is possible to install it into the JRE.

Ive been trying to figure out how to add Nashorn or another engine back to Java 16 for use with a 1.17 format map.  Any chance you could provide some instructions on how to do so?  I am not having any luck with Google.

**Comment by Captain-Chaos** [comment]
The next release of WorldPainter will include the Graal JavaScript engine so it will no longer be necessary to install it yourself (it might be necessary to adapt scripts though, as it is not fully compatible with Nashorn).
