### ISSUE TITLE
.onlyOnBiome() Not working in scripts

### ISSUE THREAD

**Issue by CarolusFPV** [Captain-Chaos/WorldPainter#192]
I made a fairly straightforward script but it seems that the .onlyOnBiome() gets ignored completely.
It will apply terrain everywhere.

Script I used:
`var Terrain = wp.getTerrain()`
    `.fromFile(path + 'Tundra.terrain')`
    `.go();`

`var Filter = wp.createFilter()`
    `.onlyOnBiome(12) //ID 12 = Snowy Tundra`
    `.go();`

`wp.applyTerrain(Terrain)`
    `.toWorld(world)`
    `.withFilter(Filter)`
    `.applyToSurface()`
    `.go();`

**Comment by MattiBorchers** [comment]
Can confirm!
Filters are not working when applying terrain.

Here is another simple example:
[terrainWithFilter.zip](https://github.com/Captain-Chaos/WorldPainter/files/8734082/terrainWithFilter.zip)

**Comment by Captain-Chaos** [comment]
Very strange. It looks like the `withFilter()` call never even reaches Java so the filter is never actually set on the operation. I wonder if this is a bug in Nashorn. I'll look into it.

**Comment by Captain-Chaos** [comment]
OK, I found a bug that explains why your script doesn't work, @MattiBorchers. It turned out to be a genuine bug, nothing to do with Nashorn. I will fix it in the next release.

By the way, there is also bug in that script. `Mask2.png` does not _have_ values up to 255, so this mapping makes no sense:

```JavaScript
	.fromLevels(0, 127).toTerrain(16)
	.fromLevels(128, 255).toTerrain(17)
```

`Mask2.png` is a 1-bit image so it only has values 0 and 1. This will work as you expect:

```JavaScript
	.fromLevel(0).toTerrain(16)
	.fromLevel(1).toTerrain(17)
```

**Comment by Captain-Chaos** [comment]
However I think that's a different bug from the problem you encountered, @CarolusFPV. At least I don't see how it could cause that symptom at the start of 2021. Does that bug still occur?

**Comment by Captain-Chaos** [comment]
Never mind @CarolusFPV, I found the bug. There was a bug specific to filtering on biomes. I'm not sure that has actually ever worked. It will be fixed in the next release. My apologies for taking so long!
