### ISSUE TITLE
updated for 1.16

### ISSUE THREAD

**Issue by tlamorod** [Captain-Chaos/WorldPainter#195]
Hey is there any way that I could have like even a beta version of world painter for 1.16?

**Comment by n8bar** [comment]
> Hey is there any way that I could have like even a beta version of world painter for 1.16?

If you don't need any handholding or support, go ahead and download the existing code and compile it, otherwise, my suggestion is that we be as patient as hell while the masters are at work.

**Comment by Captain-Chaos** [comment]
WorldPainter already works with Minecraft 1.16. This isn't really what these issues are meant for, so I'm going to close this one. If you experience specific problems though, don't hesitate to create a new issue, or ask on reddit.com/r/WorldPainter

**Comment by tlamorod** [comment]
what i meant was support for the 1.16 blocks and the new nether/overworld terrain
