### ISSUE TITLE
[BUG] Some biomes aren't exported correctly in the new 1.15 Map Format

### ISSUE THREAD

**Issue by MattiBorchers** [Captain-Chaos/WorldPainter#204]
All biomes with IDs over 127 are not exported correctly in the newest version. (After the change from 1.14 to 1.15 map format).

I made a small test world with some biomes, like Flowert Forest (ID: 132)

![1](https://user-images.githubusercontent.com/47185281/119274247-3aaed600-bc0f-11eb-9d96-479d8604395f.png)

As you can see on the Minutor render, the biomes are displayed as "unknown".

![2](https://user-images.githubusercontent.com/47185281/119274248-3b476c80-bc0f-11eb-9a13-89bd1427ff18.png)

When you open the chunk data with the NBTExplorer, the biome ID is negative, for example -124 for the Flower Forest.

![3](https://user-images.githubusercontent.com/47185281/119274249-3b476c80-bc0f-11eb-90e8-8a83464c7465.png)

**Comment by Tanerx** [comment]
Can't export my map because of this bug.

**Comment by evanthebearge** [comment]
Can confirm bug too.

**Comment by Ajaxan** [comment]
Also ran into this issue. Not getting any bigger number but smaller ones are working. Didn't test it to the same degree as the original poster, but my tests definitely support his theory. However, my biome in NBTExplorer is always set to 1 for big biome numbers and I haven't seen any negative numbers.

**Comment by sijmenvb** [comment]
![image](https://user-images.githubusercontent.com/64913742/134826953-049a618d-2169-4245-bd37-41473d764eca.png)
minecraft stores the id's as signed 2's compliment in little endian. it seems like it go's wrong in the last(little endian) 6 bytes of each 8 byte block. these should always be 00 and never be FF.

**Comment by Captain-Chaos** [comment]
This will be fixed in the next release. Thanks for your help @sijmenvb and sorry it took so long!
