### ISSUE TITLE
this is going to the moon 🚀🚀🚀

### ISSUE THREAD

**Issue by here0not0to0code** [Captain-Chaos/WorldPainter#206]
![2021-06-12_14 56 04](https://user-images.githubusercontent.com/82895073/121789918-046dd200-cb8f-11eb-956b-fe4cb3066a98.png)

For more info, I'm playing Minecraft 1,17 flying, and then I saw this big thing in my way I know any maps after 1.15 will be a bit buggy. But I don't know what made this happen

**Comment by qualk** [comment]
Bruuuuuuuuuuuuuuuuh the same bug in Infdev.

**Comment by Captain-Chaos** [comment]
I don't think that's a bug; it seems more likely that you accidentally did this yourself while creating the map. If you're sure that's not the case, can you attach the .world file that results in this when exporting it to Minecraft? And tell me the coordinates?

**Comment by Captain-Chaos** [comment]
Closing this since I never heard back.
