### ISSUE TITLE
All WorldPaint Generation Disappears in 1.17?

### ISSUE THREAD

**Issue by DoltenBolten** [Captain-Chaos/WorldPainter#207]
Weird, I have this WorldPaint-Generated World that works fine in 1.16.5, but for some reason, it all deletes itself when going into 1.17.

(my world is fine because I made backups, phew)

**Comment by Malfrador** [comment]
This sounds like the world disappears _after_ it has been exported (generated) by WorldPainter. If thats the case, its unrelated to WP and just a known 1.17 bug.

**Comment by DoltenBolten** [comment]
The world originally was exported in 1.15. It worked. I had this problem upgrading it to 1.16, but then it somehow worked after I tried loading it for the hundredth time. I now have the same problem with 1.17. I don’t understand how updating an already generated world causes everything to disappear..

**Comment by Malfrador** [comment]
As I said, anything that happens after you exported the world is unrelated to Worldpainter.

In your case it's probably this issue: https://github.com/PaperMC/Paper/issues/5910

**Comment by DoltenBolten** [comment]
Sorry, I should clarify, its a vanilla singleplayer world and the chunks do generate, its just that the chunks are natural generation, not what WorldPainter made
