### ISSUE TITLE
Option to turn off default trees when using the default biome layers

### ISSUE THREAD

**Issue by navett52** [Captain-Chaos/WorldPainter#21]
I'd like to use the biome layers to add the appropriate coloring to grass and leaves, but I have custom trees to put into the map and I would prefer there not be the default MC trees. Is there any way around that as of now that I'm unaware of? (I have looked but didn't see anything) If there isn't would it be possible to add it in?

**Comment by Captain-Chaos** [comment]
There _aren't_ default MC trees by default. Those are only generated by Minecraft if you use the Populate layer, or check the "allow Minecraft to populate the entire terrain" checkbox.

Apart from that this is not something that WorldPainter has control over. See the [FAQ](http://www.worldpainter.net/trac/wiki/FAQ#HowdoIchangewhatMinecraftdoeswhenIusePopulateHowdoIgetridofallthesmallwaterandlavalakes). If you want Minecraft to populate the terrain yet not place trees (which seems a little contradictory), the only way to do that is to use the Superflat world type with a suitable preset. See the [Minecraft wiki](http://minecraft.gamepedia.com/Superflat) for details.
