### ISSUE TITLE
GUI's broken or something?

### ISSUE THREAD

**Issue by Gavins38** [Captain-Chaos/WorldPainter#216]
![image](https://user-images.githubusercontent.com/67829574/141022194-c63f1593-cc83-4748-a868-a29d3f3d1e91.png)
Most of the guis are like this how can i fix this.

**Comment by Captain-Chaos** [comment]
Try changing to a different acceleration setting in the Preferences. If WorldPainter will not start at all any more you can start it in Safe Mode (separate Start menu entry) to change it back.
