### ISSUE TITLE
Configured Memory Not Saving Properly

### ISSUE THREAD

**Issue by SiuanSong** [Captain-Chaos/WorldPainter#218]
If I open the program after a fresh install, it uses the proper amount of RAM.  If I close the program and reopen, it defaults back to 232MB and will not change until I uninstall and reinstall the program.  This is the .vmoptions file.

`# Enter one VM parameter per line`
`# For example, to adjust the maximum memory usage to 512 MB, uncomment the following line:`
`# -Xmx512m`
`# To include another file, uncomment the following line:`
`# -include-options [path to other .vmoption file]`
`-Xmx14257M`

Fresh Install:
![worldpainter_Sl3ojgvkbn](https://user-images.githubusercontent.com/28202890/142335560-80d11d43-c1f5-4285-8bd4-058e0b444c9a.png)

After Closing and Reopening Program
![worldpainter_PB982cOhcP](https://user-images.githubusercontent.com/28202890/142335578-1cafa76e-c63e-4865-bc62-cff6b0e3c2d3.png)

I have no trouble exporting or merging maps after a fresh install.  After closing and reopening, I get the "out of memory" error.

Using Windows 10

**Comment by Captain-Chaos** [comment]
That's _very_ odd. How do you start WorldPainter?

**Comment by SiuanSong** [comment]
Checked a bit some more and the memory is only correctly maxed out to 12.5 GB when selecting Run Program at the end of the Setup wizard.  If I uncheck that and open it from the start menu, the memory is only 232 MB.

**Comment by Captain-Chaos** [comment]
Very strange. Could it be that you have multiple installations of WorldPainter and it's starting a different one from the Start menu? How is the Start menu entry configured exactly?

**Comment by Captain-Chaos** [comment]
And where is that `.vmoptions` file you quoted located?

**Comment by Captain-Chaos** [comment]
Were you the person who recently posted on Reddit about this same problem? It turned out that they had a `JAVA_OPTS` (or similar) Windows system variable set which was overriding the memory parameter. If this is still relevant could it be you have the same problem?

**Comment by Captain-Chaos** [comment]
Closing this due to age and lack of response.
