### ISSUE TITLE
Custom layer

### ISSUE THREAD

**Issue by Eisenbahn** [Captain-Chaos/WorldPainter#22]
When i click:
Custom layer so i could add bo2s trees to the map:

https://postimg.org/image/3xphazffd/

**Comment by Captain-Chaos** [comment]
Did you also email me about this problem?

**Comment by Eisenbahn** [comment]
Yes sir.

**Comment by Captain-Chaos** [comment]
It's a very strange error. How did you install WorldPainter? How do you start it?

**Comment by Eisenbahn** [comment]
The world painter Auto updater. Start double clicking its icon.

**Comment by Captain-Chaos** [comment]
Very odd. It's complaining that it can't find a component which is part of the installation and should be there. I could see there being a problem with the installer having a missing component or something, but not how you could be the only one encountering it.

Have you tried uninstalling and reinstalling?

**Comment by Captain-Chaos** [comment]
Could attach your log file (%APPDATA%\WorldPainter\logfile0.txt)?

**Comment by Eisenbahn** [comment]
Sure thing. And ill try reinstalling.
[logfile0.txt](https://github.com/Captain-Chaos/WorldPainter/files/447895/logfile0.txt)

**Comment by Eisenbahn** [comment]
Works after reinstalling.
Thank you.

**Comment by Captain-Chaos** [comment]
The log file doesn't tell me more. The most logical explanation is that something went wrong during the previous installation. Could it be your disk was full? Anyway, since it works now and there doesn't appear to be a structural problem I'm going to close the issue.
