### ISSUE TITLE
Custom biome numerical ID's not in use anymore

### ISSUE THREAD

**Issue by AllyJamy** [Captain-Chaos/WorldPainter#221]
When creating a custom biome, the box asks for a numerical ID, and only a numerical ID is possible to type in. These are not really in use anymore as they now use their names: (example minecraft:plains). 
![image](https://user-images.githubusercontent.com/23662197/145306412-2c7535c9-95c2-4694-8a9a-0c3e233c44e7.png)

Would be great if this could be changed to have the option for biome names (needed for modded biomes).

Thanks

**Comment by Captain-Chaos** [comment]
WorldPainter 2.9.0 now supports named biomes.
