### ISSUE TITLE
Worldpainter 2.8.10 Crashes when height set above 256 in preferences

### ISSUE THREAD

**Issue by DomPrice** [Captain-Chaos/WorldPainter#222]
Setting the preferences default height to anything above 256 causes WorldPainter to crash after the splash screen in normal mode (not safe mode).

**Comment by Captain-Chaos** [comment]
Thanks for reporting this!

This will be fixed in version 2.9.2.

Note that if it's still currently set to an invalid value, you may have to delete the config file (`%APPDATA%\WorldPainter\config` on Windows) once to reset the configuration.
