### ISSUE TITLE
Cant do global operations with numbers above 255

### ISSUE THREAD

**Issue by iSmokedPlutonium** [Captain-Chaos/WorldPainter#223]
Its not possible to do global operations above 255, you can say anything above 255 and it fills in everything above that, You cant say anything below 300 for example. It wont let you enter the number.

**Comment by Captain-Chaos** [comment]
@iSmokedPlutonium , this should be fixed in WorldPainter 2.9.0. @n8bar , if that is still the case in WorldPainter 2.9.0, could you file a new issue for it?
