### ISSUE TITLE
Biomes

### ISSUE THREAD

**Issue by graffityX** [Captain-Chaos/WorldPainter#225]
Biomes don't work anymore, I can spray and view them in worldpainter, but they are all vanilla plains in the end when I export them for 1.17 and view them in 1.18. A fix would be nice as this destroys many of WorldPainter's possibilites and poses a big problem to me and probably many other creatures

**Comment by GroobleDierne** [comment]
This is a known issue, 1.17 and 1.18 support are work in progress.

**Comment by Captain-Chaos** [comment]
Exporting to 1.17 and then loading in 1.18 is not supported, as you can see in the release notes. I am working on 1.18 support.
