### ISSUE TITLE
Exported 1.15 chunks uses old chunk lighting tag name

### ISSUE THREAD

**Issue by booleanbyte** [Captain-Chaos/WorldPainter#234]
I've just noticed that the 1.15 chunks exported uses the old lighting tag name "LightPopulated", for 1.15 this should be "isLightOn".

**Comment by Captain-Chaos** [comment]
Yes, good catch, although it doesn't seem to make much difference to Minecraft. Will be fixed in the next release. Thanks! 👍

**Comment by booleanbyte** [comment]
In my experience I can confirm that it does have an effect, you are just unlikely to notice it because you already expect the terrain to be lighted when it's being exported, and the end result looks very similar, if not identical, but without setting this correct, Minecraft will re-light the terrain as it understands the chunk to not already be lit, and the effort spent lighting the chunks during the export is therefore for naught.
