### ISSUE TITLE
Visual glitches in terrain preview

### ISSUE THREAD

**Issue by GroobleDierne** [Captain-Chaos/WorldPainter#235]
Hi!
I'm running Worldpainter 2.10.0 and I have some visual glitches in the preview.
![image](https://user-images.githubusercontent.com/50481621/166159977-928bd0a0-6f07-4e82-8e9f-df03ab6b4125.png)
You can see that certain tiles are duplicated and it changes every time I zoom in or out.
![image](https://user-images.githubusercontent.com/50481621/166160059-7d77ee60-a42f-44d9-9077-c8e658065255.png)
And it seems that if I zoom far enough the glitches disappears.
![image](https://user-images.githubusercontent.com/50481621/166160107-f7b0a197-4e51-43e8-8206-4856dbb78532.png)

I'm running WorldPainter on Pop Os 22.04, I updated my computer recently so I don't know if the issue is related to this or not, I will try to build a previous version of WorldPainter to find out.

**Comment by Captain-Chaos** [comment]
This looks like a bug in Java, the video driver, or Java's XRender support to me.

You can try selecting a different hardware acceleration method in the Preferences, or turning it off. Let me know if that fixes it (and if so which one).

**Comment by GroobleDierne** [comment]
You were right it stops if I select Unaccelerated or OpenGL

**Comment by Captain-Chaos** [comment]
Great, in that case I'll close this issue.
