### ISSUE TITLE
Error when exporting minecraft worlds

### ISSUE THREAD

**Issue by jmancox330** [Captain-Chaos/WorldPainter#236]
![image](https://user-images.githubusercontent.com/51308174/166160859-e82e1c6c-f215-47a1-99d5-222e720dde70.png)
Im trying to use version 1.15-1.16, and this keeps happening. It only did this after I updated to the most recent version. Please help, thanks!

**Comment by Captain-Chaos** [comment]
Fixed in version 2.9.1.
