### ISSUE TITLE
Warm Ocean biome spawns coral reefs when populate is disabled

### ISSUE THREAD

**Issue by AllyJamy** [Captain-Chaos/WorldPainter#237]
Title

Worldpainter version: version 2.9.0
Minecraft version: 1.18.2

![image](https://user-images.githubusercontent.com/23662197/166202125-7c82bfc0-fab3-40b3-8908-98920d1ca458.png)
![2022-05-02_09 50 01](https://user-images.githubusercontent.com/23662197/166202177-997f43f2-58ff-4fa3-91fa-e731dbc80b0f.png)

Export settings:
![image](https://user-images.githubusercontent.com/23662197/166202266-0dfc8d5a-2efc-4363-93a6-51a9e11e2a47.png)

**Comment by Captain-Chaos** [comment]
I can't reproduce this. There must be additional factors; can you give some detailed steps to reproduce or attach a .world file which will demonstrate the problem when exported?

![2022-05-02_11 37 55](https://user-images.githubusercontent.com/4256994/166214859-7dbe6385-af7a-492a-97d2-5553ba9d51f1.png)

**Comment by Captain-Chaos** [comment]
I guess it makes sense that you would have forgotten about that since it didn't work for years. 😉
