### ISSUE TITLE
A small issue in the datapack of the exported world.

### ISSUE THREAD

**Issue by Harveykang** [Captain-Chaos/WorldPainter#239]
![image](https://user-images.githubusercontent.com/46108547/166444921-2c0397fc-3a4f-42d2-8a47-c9c1e780a6a9.png)
`"logical_height"` Should be equal to top of ceiling minus min_ y. If there is no ceiling, it should be equal to `"height"`. 
Maybe could add an option to change it when exporting. 
[Wiki](https://minecraft.fandom.com/wiki/Custom_dimension#Dimension_type): 
> `logical_height` The maximum height to which chorus fruits and nether portalscan bring players within this dimension. This excludes portals that were already built above the limit as they still connect normally. 

😉

**Comment by Captain-Chaos** [comment]
It's not clear to me that that is not referring to height above y=0. What is the consequence if this is wrong?

It's hard to find any reliable technical details about this field. Can you point me to any (that isn't just copied from the wiki, or unsourced)?

**Comment by Harveykang** [comment]
I will test and take screenshots tomorrow(Beijing time). 😃

**Comment by Harveykang** [comment]
Maybe I can send these out before going to bed.
When players enter a built portal, if there is no portal in the corresponding range, a new portal will be generated. 
`"logical_height"` controls the generation range of these portals from min_y. 
A value greater than the world height will prevent you from loading the world. 
**Too low a value will cause the game to enter an endless loop when generating a new portal.** 

Normally, the new portal cannot generated above the nether ceiling. But if we set a higher `"logical_height"` of the nether, and the entrance portal is high enough, it will happen: 
![3E6QH`MYQXYJA~QEX}~ 6A5](https://user-images.githubusercontent.com/46108547/166496134-04f749bb-d4f7-4a98-a9cd-dda655136313.png)
entrance portal

![709ZV1({P__%MOWGP~TR61D](https://user-images.githubusercontent.com/46108547/166496150-e50df59a-1b58-4605-aed0-1880a91715a7.png)
normally

![$JAYK@I{FRF3 4IBQ0M5%QJ](https://user-images.githubusercontent.com/46108547/166496160-775866da-c0c5-4f76-b957-02156507869f.png)
modified the `"logical_height"`

Similar for overworld: 
![)I%VUJTCG%1O1 ~%4N(OV40](https://user-images.githubusercontent.com/46108547/166499077-fe85f279-6e65-46c2-bcce-25eee89b81ca.png)
entrance portal

![2 G6S)BOLJ 4O6N0UUZTXV](https://user-images.githubusercontent.com/46108547/166499098-21d069e5-7159-4fc8-b735-bad79b2131e6.png)
normally

![MJ0AD~A~QG 5UOEB5L30~EP](https://user-images.githubusercontent.com/46108547/166499113-d5e05546-f8f5-4bf7-8978-97d689fd62f9.png)
modified the `"logical_height"`

**Comment by Harveykang** [comment]
It is certain that the generation range is calculated from `min_y` to `min_y+logical_height`, because even if the `logical_height` is set to 128, the protal the portal can still not be generated on the surface. 
![image](https://user-images.githubusercontent.com/46108547/166609406-b403b0a1-9a05-41f1-963a-5364b4c656a2.png)
![image](https://user-images.githubusercontent.com/46108547/166609740-1ba2ba6a-5ae8-46d4-bffd-138a9d312791.png)

**Comment by Captain-Chaos** [comment]
Alright, you've convinced me. 😉 Will be fixed in 2.9.3.

Is it not a problem if this value is very high? Won't Minecraft generate floating portals far above the terrain? Or does it still try to find the terrain surface?

**Comment by Captain-Chaos** [comment]
I will set it equal to `height` for now. Trying to take a ceiling dimension into account is much more complicated; can you file a separate feature request for that?
