### ISSUE TITLE
Filenames are cut off from the first “.”, instead of the last. 

### ISSUE THREAD

**Issue by Harveykang** [Captain-Chaos/WorldPainter#241]
![image](https://user-images.githubusercontent.com/46108547/166682821-7f4ecf84-e952-4570-b199-77c54901823c.png)

![HD1`LELCK0LEL(NON QQ97D](https://user-images.githubusercontent.com/46108547/166682790-0d7a6f14-8d47-4a16-827a-eec04f86d220.png)

**Comment by Captain-Chaos** [comment]
When exactly is this? When importing a height map?

**Comment by Captain-Chaos** [comment]
Thanks for the report. Interesting problem. It's actually not cutting off from the first '.'; it's cutting off from the last one _twice_. 😀

Will be fixed in release 2.9.3.
