### ISSUE TITLE
[Feature Request] Make the “logical_height” of ceiling dimensions be calculated from ceiling heights. 

### ISSUE THREAD

**Issue by Harveykang** [Captain-Chaos/WorldPainter#242]
Normally, `logical_height` is equal to the total height from the lowest to highest blocks in ceiling dimensions. 
For example, the vanilla nether is generated from y0 to y127, so the `logical_height` is 128.

**Comment by Captain-Chaos** [comment]
I don't think this is relevant any more now, right? Feel free to reopen it if it is!
