### ISSUE TITLE
[Feature Request] Is it possible to set the world bottom lower than -64 until -2032?

### ISSUE THREAD

**Issue by Harveykang** [Captain-Chaos/WorldPainter#243]
Since Minecraft 1.17, 
`min_y` can be set from -2032 to 2031, 
`height` and `logical_height` can be set from 0 to 4064.

**Comment by crthpl** [comment]
there should also be a slider, so that one is not restricted to the world height presets.

**Comment by Captain-Chaos** [comment]
Even though #278 is newer I'm closing this one as a duplicate of #278 to consolidate demand for this feature. Feel free to add a +1 there to gauge support for this.

**Comment by Captain-Chaos** [comment]
Duplicate of #278
