### ISSUE TITLE
Problem with hidden layers

### ISSUE THREAD

**Issue by CaliberMC** [Captain-Chaos/WorldPainter#247]
I am having an issue with unhidding layers that are part of a combined layer.  When I deselect the hidden option, the layers are staying hidden.  It appears to be sort of random, some of my layers allow me to unhide them while others refuse to unhide.

**Comment by CaliberMC** [comment]
Also seems to be intermittent.

**Comment by Captain-Chaos** [comment]
I did a quick test but could not reproduce this. (I did notice a problem with _hiding_ the layers in the first place.)

Could you give some detailed steps to reproduce? Starting from a fresh, empty world, or from a world file you attach?

**Comment by CaliberMC** [comment]
Yes, hiding layers seems to not work sometimes.  I may have accidentally renamed my layers rather than duplicating them, as I am not able to reproduce it now either, unless something got fixed in the last update.
