### ISSUE TITLE
Add barrier wall option when exporting

### ISSUE THREAD

**Issue by Scratchyerik** [Captain-Chaos/WorldPainter#248]
Not sure where to put this but I'm trying to prevent water from flowing off the sides of my map which causes immense lag as the blocks update and flow into the abyss. A barrier wall option would be nice alternative to a ugly Bedrock wall.

**Comment by Captain-Chaos** [comment]
Yeah that makes sense; I've thought of that before myself as well. Simple to do, so as good a time as any. 😀

**Comment by Captain-Chaos** [comment]
This will be added in the next release.
