### ISSUE TITLE
[Feature Request] Multiple Image Overlays

### ISSUE THREAD

**Issue by Til-Weimann** [Captain-Chaos/WorldPainter#252]
Hello!

This is just a minor request, nothing critical at all, but it could be useful to have the ability to overlay more than one image at a time and toggle them individually.

This way, you could not only build your world based on multiple data sources at once, the tedious task of entering new scale and position settings every time you want swap images would also disappear.

As I said, this is not too important and many other things probably have priority right now, but I'll still just leave this idea here just in case.

**Comment by n8bar** [comment]
I really need this for a project I've been dreaming up.

**Comment by Captain-Chaos** [comment]
This will be added in the next release.
