### ISSUE TITLE
World I created in 2.8.10 cannot be opened 2.10.5

### ISSUE THREAD

**Issue by MisterQuiggly** [Captain-Chaos/WorldPainter#256]
![Error message](https://i.imgur.com/ISOCtfB.png)

I created this world in 2.8.10 and it was created using the Cubic Chunks Plugin version. You can see in the error message that I used the plugin 'CubicChunksPlatform (1.2.0-WP2.7.0)' which worked just fine in WP 2.8.10. That plugin is still installed and it still allows me to create a cubic chunks world in WP 2.10.5. 
The file obviously wasn't created with a newer version of world painter, it was created in a slightly older version.
The file is not damaged or corrupted because I can open it just fine in an older version of WP I found on my computer (2.8.1). 

Ideally, I'd like to be able to use this file in the latest version of WP as I've put a lot of work into it and would like to keep using it in the latest version of the program and of the game. I don't even want to use the Cubic Chunks world type anymore. I instead want to export it as a vanilla world with the new supported customizable world height. I had no problem exporting this world as a vanilla world with a higher build height in WP 2.8.10. I am not done working on this world and also WP 2.8.10 files exported for 1.17 do not open in 1.18 properly. 

If this cannot be fixed then I would at least like a copy of WorldPainter 2.8.10 as I no longer have it since it got overwritten by the newest version and there doesn't seem to be a page for older downloads on your website. I have 2.8.1 but I rather not use that and would rather use the latest one I had last used.

**Comment by MisterQuiggly** [comment]
![New Error Message](https://i.imgur.com/cZZj27c.png)

The Cubic Chunks team released an update at some point for plugin version 1.3.0. This version also does not work; I tried loading the world into an old version of WP and then opening it in the latest and I get the same error.

If you are going to need my .world save file then I would prefer to email it to you instead of linking it here publically where anyone can get it. Alternatively, again if you need it, I could send a download link to your discord, Captain Chaos#3239, if you still use that discord.

**Comment by Captain-Chaos** [comment]
The CubicChunks plugin is not compatible with the latest version of WorldPainter; it needs to be updated by the author. However I'm not convinced it's the cause of this error. If the plugin is present it should at least still load the world.

Can you upload your log file (`logfile0.txt`)?

**Comment by Captain-Chaos** [comment]
And can you confirm that the CubicChunks plugin is actually being loaded (it should be listed on the Tech Info tab of the About screen)?

**Comment by Captain-Chaos** [comment]
Since it's not unlikely this is some kind of bug, also go ahead and send me the .world file. You can email it (or a link) to support@worldpainter.net if you wish (link to this issue so I know what it's regarding).

**Comment by MisterQuiggly** [comment]
I have emailed you the world file and logfile0.
Thanks

**Comment by Captain-Chaos** [comment]
Thanks! As I suspected, the cause of the error is not that it is a CubicChunks world, at least not directly. This world has a strange provenance. I can't explain how, but it has the world type set to Superflat, even though the CubicChunks plugin does not support that, and somehow the Superflat preset is empty (which is the cause of the error).

What I will do is implement a workaround in the next release which will reset the Superflat preset to default settings when that happens. You will then be able to open the world file and change the map format to something else, without even needing the CubicChunks plugin.
