### ISSUE TITLE
Indroduce a Task System in WorldPainter

### ISSUE THREAD

**Issue by frogocomics** [Captain-Chaos/WorldPainter#26]
My proposal for WorldPainter is to implement a task system, where a tasks are created, and run one after the other. I believe WorldPainter should have this because of this important reason:
- Terraformers constantly have to deal with large maps (10000+ x 10000+), and therefore operations such as global operations because increasingly slow. The task system can make it so that the user (terraformer) can specify as many global operations as they want while their first operation is being processed. Then the task manager executes the tasks one by one in order. This could be a massive time saver for terraformers as they could specify multiple global operations (or other operations), and all of the specified operations will be executed one after the other.

I have started the creation of the `TaskManager` and `Task class`, and I will be making a pull request soon. I would appreciate it if no changes are made to WorldPainter for a day, so I could make a pull request WITHOUT CONFLICTS. (I still don't know how to resolve conflicts).

I would appreciate if feedback and improvements could be made on this, as I think it could make for a easier user experience. My currently progress is on my fork of WorldPainter.

**Comment by frogocomics** [comment]
I've basically finished creating it, and I would like someone to point out mistakes in my code (if any). I would also appreciate advice. I will make the pull request tomorrow.

**Comment by Captain-Chaos** [comment]
I propose to close this issue, as there doesn't seem to be much progress, and you don't really need an issue in WorldPainter to be able to work on it in your own fork.

In addition, while I agree that the premise of being able to queue multiple operations for execution in the background could be very useful, I think this needs to be thought out in a little more detail functionally before implementation. There are questions such as whether you should still be able to edit the world live, and if so how that should work, and there is also the question of whether scripting isn't more suitable for things like this.

**Comment by frogocomics** [comment]
Of course. Let me know if you have a better way to do this.
