### ISSUE TITLE
 Can't set some "Decorations" in the preferences

### ISSUE THREAD

**Issue by MattiBorchers** [Captain-Chaos/WorldPainter#261]
As you can see in the screenshots, I am not able to set some decorations in the preferences Windows.

![wp-caves-preferences](https://user-images.githubusercontent.com/47185281/175063042-e4638aad-b9f8-4db5-959a-623a6bedc851.PNG)

When exporting the map, the checkboxes are enabled, so I can use them.
The only problem: the preferences are used for the scripting engine, so at the moment I can only use this options in the GUI.

![wp-caves-export](https://user-images.githubusercontent.com/47185281/175063045-6eb6f325-b085-4bf2-b686-9f25686b4e12.PNG)

**Comment by MattiBorchers** [comment]
Mh, my default world setting is "Minecraft 1.18 or later", so it should be the correct format.
And it doesn't matter what format I chose, it is always disabled.
![default_world_settings](https://user-images.githubusercontent.com/47185281/178302596-3cbd27dd-0047-444b-9093-9a1542fdd0e5.png)

**Comment by Captain-Chaos** [comment]
Interesting. That does sound like a bug; I'll look into it.

**Comment by Captain-Chaos** [comment]
I didn't get at first that you were literally talking about the Preferences screen, but once I did I could reproduce this. It will be fixed in the next release.
