### ISSUE TITLE
[Linux] WorldPainter is completely broken on Wayland/XWayland.

### ISSUE THREAD

**Issue by nikkedoy98** [Captain-Chaos/WorldPainter#263]
When I try painting, rising terrain or do anything with WorldPainter it doesn't work as expected.
Here are some specs:
- [WorldPainter] version 2.10.13 (installed through install.sh-script)
- [DE] KDE Plasma version 5.25.3 (Wayland and X11)
- [Java] Java 17 (Java 8 also tested)
- [Kernel] 5.19.0-rc6-tkg-tt (shouldn't affect this, but here it is)
- [Distro] Artix Linux (and yes. This shouldn't affect anything as well)

E.g. This is what happens when you try to paint (using Wayland):
![on_wayland](https://user-images.githubusercontent.com/42248504/179361234-e8bea0a1-e6f9-483f-a0e9-d7f4558ab3ad.jpeg)

And this is what it should look like (using X11):
![on_x11](https://user-images.githubusercontent.com/42248504/179361237-cd7614ad-54bd-4ff4-af47-34edc6731335.jpeg)

Does anyone else have this problem or is it just me?

**Comment by Captain-Chaos** [comment]
I'm not familiar with Wayland. Can you clarify: is the problem an input problem or an output problem? Does it not respond correctly to mouse input, or does the output glitch?

In the first case, could you you try [this](https://www.worldpainter.net/trac/wiki/AdvancedSettings#AlternateInputMethod) advanced settings to disable tablet support and switch to an alternate input method?

In the latter case, could you try alternate acceleration methods on the Performance tab of the Preferences?

**Comment by nikkedoy98** [comment]
Yes. It's a output problem. When I'm holding left mouse button down and dragging it to draw, but it doesn't draw. Just draws nothing or makes one circle (depends on what brush is used ofc.)

**Just tried to disable tablet support and it worked! Holy moly!**

I've tested this on Ubuntu 22.04 virtual machine and WorldPainter worked just fine there 🤔. This is probably just "plasma moment." I'll close this issue and hopefully someone else finds this useful if the encounter this exact problem.

**Comment by Captain-Chaos** [comment]
I'll add a check to WorldPainter so that it automatically disables tablet support on Wayland, since it's unlikely that that will ever work given the age of the library I use.
