### ISSUE TITLE
dimension.getHighestX/Y is wrong (sometimes)

### ISSUE THREAD

**Issue by IR0NSIGHT** [Captain-Chaos/WorldPainter#266]
Tested on the default 5x5 grid space:
starts at -256,-256; ends at 384,384

dimension.getHighestX returns 256; should be 384
dimesnion.getHighestY returns 256; should be 384

dimension.getWidth/Height acts as proper substitute

Reloaded map at least once
Works fine on my other map (but that onces circular, might be the reason)

**Comment by Captain-Chaos** [comment]
> dimension.getHighestX returns 256;

`Dimension.getHighestX()` and `getHighestY()` return tile coordinates, not block coordinates. It should return something like 2, not 256, so if it does then _that_ would be a bug, but looking at the code that seems highly unlikely. Can you please re-evaluate, and provide a test case if you really think there's a bug?

**Comment by Captain-Chaos** [comment]
I'll close this since I haven't heard from you. Please feel free to open a new issue if you still think there is a bug!
