### ISSUE TITLE
1.18.2+ Merge function gives "Array index out of bounds" in some cases

### ISSUE THREAD

**Issue by Ikelosian** [Captain-Chaos/WorldPainter#267]
### 1.18.2+ Merge function gives "Array index out of bounds" in some cases
I have encountered an issue with the merge function that ive been able to replicate reliably in versions **1.18.2+** (as of august 2 2022)
Ive verified the issue with multiple people. We have used the latest versions of worldpainter (including a test today of 1.16 to 1.19 with version 2.12). This issue affects worlds that are **"heavily modified"** from my observation, but the best way ive found to replicate the issue is to simulate heavily modified words by importing one world and merging it with a different one

### The steps to easily replicate are as follows:
  1. Prepare two vanilla generated non-flat worlds
  2. Load one world into worldpainter version 2.10+ with no chunks marked as read only
  3. Use the merge function to merge with the other world prepared in step one using default settings
  4. Observe that after the merge operation, several Array index out of bounds errors are thrown, either -1 or 24 from range of 24 from my testing. Opening the world in a program such as unmined shows missing / corrupted chunks
 
### Notes:
Merging the same world without changes to itself will not throw errors
Merging the same world with heavy modifications will throw errors (this is the situation in which i discovered the issue)
Using option "mark chunks containing manmade blocks read only" will not throw errors
Some example errors strings: 
`Array index out of bounds while reading chunk in existing map 31, 23 from region java.awt.Point[x=-1,y=0] (message: "Index -1 out of bounds for length 24"); skipping chunk`
`Array index out of bounds while reading chunk in existing map 22, 17 from region java.awt.Point[x=-8,y=4] (message: "Index 24 out of bounds for length 24"); skipping chunk`

### My guess? 1.18.2 level format changes
No coder, but i do know that the level format got some changes in 1.18.2. Possible cause for this issue

**Comment by shimajima** [comment]
I am able to reproduce this problem as well. Happens when merging any worlds 1.18.2 or above if you select the merge option: "Do not mark any chunks read-only" (see screenshot). If you use the default merge option "Mark chunks containing man-made blocks above ground read-only" then the errors are not encountered. Or if you use worlds that are 1.18.1 or below then no errors.

![image](https://user-images.githubusercontent.com/61395186/182508754-c60256c7-7acc-437e-9393-7f5e48df39b7.png)

**Comment by Captain-Chaos** [comment]
@shimajima, @shimajima : it's not really clear to me when these errors occur exactly, or how to reproduce them (what are "heavy modifications"?). Both Import and Merge are mentioned, and @shimajima, you specifically talk about merging, but the setting you mention and the screenshot you post are for Importing.

Can either or both of you attach a test case for me? In the form of either:

- A Minecraft map that will give these errors when I Import it, or:
- A Minecraft map and a .world file which will give these errors when I attempt to Merge it with that map?

Many thanks in advance!

**Comment by Ikelosian** [comment]
@Captain-Chaos Sure! I detailed some steps to replicate in my initial post, but for connivence here is a [Verification_Package.zip](https://drive.proton.me/urls/D4BPD3DM1C#p0fbwZkDlP6b) containing the files needed for easy replication, as well as a readme.md giving the procedure to follow.

**Comment by shimajima** [comment]
@Captain-Chaos thank you so much for investigating this. Just to be clear, the repro steps I'm using are:
(1) Import @Ikelosian's Smallbiome1 1.19.1 world into WP (using option "Do not mark any chunks read-only")
(2) Merge with @Ikelosian's Smallbiomes2 1.19.1 world (taking all default merge options)
(3) Merge produces the "Array index out of bounds" errors

**Comment by Captain-Chaos** [comment]
@Ikelosian Thanks! It makes a huge difference to the speed with which I can fix an issue if I can just immediately reproduce it.

**Comment by Captain-Chaos** [comment]
Alright, I've found this bug and it will be fixed in the next release. Thanks for your help!
