### ISSUE TITLE
Diffuse casting error on scripting api

### ISSUE THREAD

**Issue by IR0NSIGHT** [Captain-Chaos/WorldPainter#271]
Latest update (2 days ago?) causes script to fail with attached error.
Have not investigated which part causes the error, someone mentioned it seems to be
"world.getDimension(0)" 

![grafik](https://user-images.githubusercontent.com/32139214/186411866-9edd7221-be15-4278-b1c4-2af6508dd822.png)

**Comment by Captain-Chaos** [comment]
Yes, the signature of that method has changed. It no longer takes an integer, but an Anchor, which encodes more information.

This is internal code, not public API, so this can always happen. Also remember that scripts running in WorldPainter already have access to the currently loaded dimension via the `dimension` global variable.

However I have already decided to reintroduce this method in the next release, to prevent this problem. It will be deprecated, but there is no reason why it can't still function. You just won't be able to use it to access additional dimensions in the future.
