### ISSUE TITLE
[Bug] Custom layers not importing on worldpainter 2.15.0

### ISSUE THREAD

**Issue by darthpeti** [Captain-Chaos/WorldPainter#276]
I have recently updated my worldpainter version and exported a custom world made on WP that used rivers as custom ground cover layers. On 2.14.6 , the river would be normal on the map, and it would look like this: (first image)
![image](https://user-images.githubusercontent.com/95631000/195871027-f1f827ed-4552-4ee9-960f-216cb8ff3ffb.png)
However, on WorldPainter version 2.15.0, the river would look like this, while exporting with the same settings and values: (second img) 
![image](https://cdn.discordapp.com/attachments/1019307014154883175/1030479430528815134/unknown.png)

I fixed my map by downgrading my worldpainter version, but i thought it would be nice to report this bug so it doesn't go unnoticed.
Anyways, thanks for providing this awesome tool. WorldPainter seems like a very cool thing and I love using it almost every day.

**Comment by darthpeti** [comment]
i also noticed the plants and tree layers weren't imported, except for the default ones provided by WP already

**Comment by darthpeti** [comment]
exported* sorry

**Comment by Captain-Chaos** [comment]
What do you mean by "importing"? Are you saying that if you Export a .world file on WorldPainter 2.15.0, all the water and trees are missing, but if you Export the same .world file on WorldPainter 2.14.0, they are there? Could you attach that .world file please?

**Comment by darthpeti** [comment]
sorry, i meant exporting. and by that i mean that if i use a custom layer, like for example a plants layer, and paint it all over the map, there will actually be no plants in the map when i export the world as A Minecraft Map

**Comment by darthpeti** [comment]
> What do you mean by "importing"? Are you saying that if you Export a .world file on WorldPainter 2.15.0, all the water and trees are missing, but if you Export the same .world file on WorldPainter 2.14.0, they are there? Could you attach that .world file please?

i'm not sure if i can attach it here publicly. is there somewhere where i can send you a download link privately for the worldpainter file? it's well above 200MB

**Comment by Captain-Chaos** [comment]
You could DM me a link on Reddit, or mail it to support@worldpainter.net. Reference this issue so I know what it is regarding.

**Comment by darthpeti** [comment]
Alright, I'll E-mail you the download link in a second

**Comment by darthpeti** [comment]
I sent it

**Comment by darthpeti** [comment]
Was the issue found? Or is it still being investigated?

**Comment by Captain-Chaos** [comment]
I released a new version last night in which some related bugs were fixed; could you check whether your issue still exists?

**Comment by darthpeti** [comment]
I'll try it.

**Comment by darthpeti** [comment]
It seems like it's fixed. I opened the map with an overviewer since I couldn't launch MC and I can once again see the rivers, trees and vegetation on the map. Thanks for all the support!
![image](https://media.discordapp.net/attachments/1019307014154883175/1030732262788038696/unknown.png)

**Comment by darthpeti** [comment]
Should I close this issue if everything is fixed now?

**Comment by Captain-Chaos** [comment]
Sure, if you're confident that your issue was fixed.

**Comment by darthpeti** [comment]
Thanks.
