### ISSUE TITLE
Add a way to increase the Minimum height limit of the world.

### ISSUE THREAD

**Issue by Peregrine05** [Captain-Chaos/WorldPainter#278]
Currently, the deepest the world can be set to is *-64*. Add a way to set the Minimum height limit to be deeper than the 1.18 default of *-64*. Minecraft supports this via datapacks, and since WorldPainter already supports increased maximum height limits with datapacks, increased minimum height limits should be easy to implement.
![image](https://user-images.githubusercontent.com/92183530/197796452-f702a1d6-ddd4-4057-b919-b9c72ffba1be.png)

Related to #243.

**Comment by Captain-Chaos** [comment]
This is not as trivial as you think. The maximum build height is now flexible in the WorldPainter codebase, but the minimum build height is not. It would require significant additional work to make that as flexible, and there is very little demand for it. I'll leave this open, but I would not count on it any time soon.

**Comment by Captain-Chaos** [comment]
Picking this up now, since it's a quite popular request. Just a heads up though: I'm working full time again so this will be happening in my free time and might take a while.

**Comment by FETXU** [comment]
> Picking this up now, since it's a quite popular request. Just a heads up though: I'm working full time again so this will be happening in my free time and might take a while.

You are amazing, thank you for making some time :)

**Comment by Captain-Chaos** [comment]
I have a first working iteration. I would be grateful if everyone in here would test it. You can download the Windows 64 build [here](www.worldpainter.net/files/worldpainter_2.17.0-SNAPSHOT.exe). Change the filename for other editions, or ask me for the link.

Please test whether the new configurable lower build limit works with all WorldPainter features, and also whether exporting works correctly and can be loaded in Minecraft successfully. I understand that you would like to be able to transform it to bedrock, @FETXU, so please test that as well. Also look out for missing adaptations to the new configurable lower build limit.

Let me know in here when you encounter any problems!

**Comment by FETXU** [comment]
Amazing work friend!!!

I will def be testing and will report back as soon as possible.
