### ISSUE TITLE
[Feature Request] "Terrace" Flood Tool

### ISSUE THREAD

**Issue by Til-Weimann** [Captain-Chaos/WorldPainter#279]
Basically like the Fill / Flood tool but with the exception that a decrease in height will act as a border just as an increase.
The effect should be that only the adjacent area of the exact same height is filled.

This would e. g. make filling a sloping river bed with water **a lot** easier, currently this is extremely tedious.
Using the regular tool isn't an option in these cases, as e. g. attempting to fill a stream going down a mountain would flood the entire valley.

**Comment by Captain-Chaos** [comment]
I see what you mean, but I don't think this is workable. It would be extremely niche, and probably also still not be that useful as it would still require many finicky clicks. There are better ways of creating rivers, such as using a Custom Ground Cover layer with water as the material and a negative thickness. I think niche applications like this are better served by scripts. I may consider changes to the scripting tool to make it easier to use it for purposes such as this.

I do concede that creating rivers is a weak point of WorldPainter; I have yet to come up with a good, flexible and powerful yet easy and simple way of doing it. But I don't think this is it, sorry.
