### ISSUE TITLE
Missing materials

### ISSUE THREAD

**Issue by Ivain** [Captain-Chaos/WorldPainter#28]
Sometimes, when creating custom materials, there seems to be some sort of bug which results in certain blocks in the custom material not existing. The resulting effect is similar to how 1.9 blocks used in terrain would not show up in 1.8.

However, cobblestone and obsidian, the 2 blocks I have had this happen with, are definitely not new blocks.
A possible cause may be from too much importing of the custom terrain, but there seems to be no discernible pattern on which ones grow buggy.

**Comment by Captain-Chaos** [comment]
Could you send me a .world file which displays this behaviour when exported? (Let me know exactly which material is missing in the export.)

**Comment by Captain-Chaos** [comment]
Are you still experiencing this? Without more information I'm going to have to close the issue.

**Comment by Ivain** [comment]
I do not think I have experienced this since, so If I come across it again I'll prepare the worldfile rightaway before opening another ticket.

**Comment by Captain-Chaos** [comment]
Alright, then I'll close the issue for now. Feel free to submit a new one if it reoccurs.
