### ISSUE TITLE
After clicking tools the screen wont work. 

### ISSUE THREAD

**Issue by hunhun86j** [Captain-Chaos/WorldPainter#280]
Hello, Id like to address a problem. When ever I click tools World painter does not work. I can move the mouse, but I can not click anything. The brush wont move and I tried to with my touch-screen (did not work). I am on a laptop, Java is updated. Please help.

**Comment by Captain-Chaos** [comment]
Maybe the touch screen is causing the problem. Could you try using [this](https://www.worldpainter.net/trac/wiki/AdvancedSettings#AlternateInputMethod) advanced setting to disable tablet support?

**Comment by Captain-Chaos** [comment]
Did you try it? Let me know if you need assistance.

**Comment by hunhun86j** [comment]
How do you execute Dorg.pepsoft.worldpainter.disableTabletSupport=true? Btw
thank you for the help

**Comment by Captain-Chaos** [comment]
You don't execute it, you add it to the `worldpainter.vmoptions` file, and you missed out a `-` at the start. Read the start of the page carefully.

**Comment by Captain-Chaos** [comment]
Did you manage it?

**Comment by Captain-Chaos** [comment]
I'll close this since I didn't hear back from you. Don't hesitate to let me know if there's still a problem.
