### ISSUE TITLE
Feature request: Heightmap view

### ISSUE THREAD

**Issue by Fornad95** [Captain-Chaos/WorldPainter#282]
Inspired by [this post](https://www.reddit.com/r/Worldpainter/comments/yteina/ive_been_utilizing_the_theme_feature_as_an/), I'd like to request a heightmap view feature. This would have two formats:

-	Greyscale (already supported by WP as an export function, although it's currently not perfect as outlined below)
-	Full colour (a variety of colour schemes could perhaps be supported, but I'd suggest something like [this](https://i.imgur.com/r5TI6g1.png) as a starting point)

Many people struggle to 'read' contour lines - heightmaps are a much more intuitive way of displaying elevation data, especially at a large scale.

The only issue I can foresee currently is that heightmaps for maps above 256 blocks have to use 16 bit rather than 8 bit images, meaning they only use the lowest values in 65,536 available values. This results in an image which just looks black. I have been able to fix this by stretching the values across the histogram in GIMP using the 'Stretch Contrast HSV' function, but WP would have to do this natively.

**Comment by Captain-Chaos** [comment]
This turned out to be pretty simple to do, so there will be an initial implementation in the next release. If I get feedback in future I could change the palette and/or provide multiple palettes or the ability to define your own.
