### ISSUE TITLE
go() method not working for the getMapFormat() operation

### ISSUE THREAD

**Issue by Quozul** [Captain-Chaos/WorldPainter#283]
I am using the JavaScript scripting API of WorldPainter with the following script: 

```javascript
var platform = wp.getMapFormat('')
  .withId('org.pepsoft.anvil.1.19')
  .go();

var heightMap = wp.getHeightMap().fromFile('heightmap.png').go();

var world = wp.createWorld()
  .fromHeightMap(heightMap)
  .toLevels(-64, 319)
  .withMapFormat(platform)
  .go();
```

However the execution of the script stops right after this with the following stack trace: 

```javascript
java.lang.IllegalStateException: You forgot to invoke go() on the getMapFormat() operation
        at org.pepsoft.worldpainter.tools.scripts.ScriptingContext.checkGoCalled(ScriptingContext.java:197)
        at org.pepsoft.worldpainter.tools.scripts.ScriptingContext.getHeightMap(ScriptingContext.java:130)
        at org.openjdk.nashorn.internal.scripts.Script$main.:program(main.js:5)
[... more lines]
```

From what I've looked at, there is a `goCalled();` missing in [GetPlatformOp.java#L23](https://github.com/Captain-Chaos/WorldPainter/blob/master/WorldPainter/WPCore/src/main/java/org/pepsoft/worldpainter/tools/scripts/GetPlatformOp.java#L23). Unfortunately, I cannot manage to compile WorldPainter to fix this myself.

**Comment by Captain-Chaos** [comment]
Thanks for letting me know! I'll fix that in the next release.
