### ISSUE TITLE
Request for eyedropper-tool

### ISSUE THREAD

**Issue by PlasticTasticc** [Captain-Chaos/WorldPainter#285]
Essentially, when using the "only on" or "except on" checkbox features, instead of looking for your designated block through a bunch of sub-categories when handling many custom blocks or custom layers. Use the eyedropper tool to directly sample the block or layer you want to use.

**Comment by Captain-Chaos** [comment]
This is a great idea. Working on it.

**Comment by Captain-Chaos** [comment]
This will be included in the next release.
