### ISSUE TITLE
Request for multiple options in only on/except on.

### ISSUE THREAD

**Issue by PlasticTasticc** [Captain-Chaos/WorldPainter#286]
Essentially just that. Could be done with a checkbox just before the name of a block or layer appears. As such being able to check many blocks to only affect or not affect at once would be a huge help for someone like me that use a lot of colors in my worldpainter maps. 

With such an option, a "clear selection" button would be very helpful too, but not as necessary IMO.

**Comment by Captain-Chaos** [comment]
This certainly makes sense. Unfortunately it would be pretty complicated to implement, for something that is pretty advanced.

How far can you get using the Global Operations and the selection? For example if you want to paint where two layers are present you could:

1. Clear the selection
1. Use Global Operations to add everywhere layer A exists to the selection
1. Use Global Operations to remove everywhere layer B _doesn't_ exist from the selection

The selection now contains the areas you want to paint, which you could then do with Global Operations, or manually.

Similarly, if you want to paint where multiple layers _don't_ exist you could:

1. Add everywhere to the selection
1. Remove everywhere layer A exists from the selection
1. Remove everywhere layer B exists from the selection 

Would this approach suffice for now?

**Comment by PlasticTasticc** [comment]
It can certainly be achieved what I want, but it's a lot of steps with a lot of scrolling through this and that to get it all right, (subtracting/adding to the final mask). And what you're suggesting doesn't bear any new benefits as far as I'm concerned. 

The primary reason I'm asking for this is to speed up my workflow, and use Worldpainter more intuitively, like it'd be second nature such as 3D software like Blender is to me. (On the same note that's also why I requested configurable hotkeys, as they speed up the workflow (see issue #310)). 

To summarize, I can get all the way using the suggested method, which is already quite similar to the technique I have been using so far, the issue is that it takes a lot of time that could easily be optimized with that simple feature. 
To circumvent having to implement what would apparently (I'm no code expert, so I'm just going off the info you gave) be an arduous task, I see 2 features that might function as a substitute if easier to implement on your part:

1. As mentioned earlier, "hotkeys", (the issue # associated with that, explains it very well I think).

2. Not mentioned earlier but just came to mind and made all the sense in the world: "show selectables as icons", as opposed to the list that it currently is-

-Imagine basically a window popping up whenever using the eyedropper tool sorta like Windows file explorer, where layers are shown as big icons, that you'd be able to scroll down through if you have a sufficient amount of layers/blocks to warrant a scroll.



However, if you'd have to prioritize what to implement, I'd say hotkeys (#310) solely. It would nearly eliminate all of the problems with this issue (#286).

**Comment by PlasticTasticc** [comment]
Say I were to just keep using the current method to paint only on and except on to include/exclude to get the right selection as a layer, similar to how you suggested using the global operations, etc. All of that has some downsides as to why I thought in the first place that more options were the way to go:

A big part of what makes it so slow is that manually I have to drag (yes, _drag_... #firstworldproblems) my mouse cursor over to the button "only on/except on" click that button once, then select "eyedropper" to then click and select the block/layer I want to select for the only/except. Not to mention also clicking the tiny button that is the paint option. That's 5 clicks with my mouse (I counted), and making sure I clicked the right way (if you have unsteady hands/fumble fingers and click somewhere and accidentally move the mouse cursor a bit at the same time it won't register the click properly).

As I mentioned earlier, the primary reason I wanted to suggest multiple options in the first place was that It's slow and finicky to manually select a new layer, add/remove to the old layer, and repeat until I have a final version of a layer (read: "mask"), I can use to paint the blocks I wanted all along.

As such, imagine instead of all that clicking, making sure my hands are steady, and dragging the mouse cursor back and forth, I could instead just use a hotkey to for example open the only/except menu (different key for each), then a hotkey combination to select the eye-dropper tool, drag my mouse cursor once and select whichever block/layer I might need, then ctrl + backspace to fill in the selection, et voila! 

Or roughly something along those lines. It could of course be much simpler at the very get-go, so I might only be able to configure the tools and not brush settings options too. 

---

Hopefully, that shed some light on my logic in assuming the hotkey feature might solve most of the problems.

**Comment by Fornad95** [comment]
Related to this, a 'clear all layers' brush would be really useful.

**Comment by Captain-Chaos** [comment]
> Related to this, a 'clear all layers' brush would be really useful.

That doesn't seem that related, but it certainly makes sense. Would you mind filing a separate enhancement issue for that?

In the mean time you could use selections together with the "reset terrain and layers to theme" global operation, although I guess that also resets the terrain.

**Comment by Captain-Chaos** [comment]
I'm working on this. How would you expect it to work if you select multiple values? What seems to make sense to me the most is "AND" logic:

For "only on": _all_ selected values should be present (e.g. if you select Frost and Forest Biome, it will paint only where _both_ are present). 

For "except on": _none_ of the selected values should be present (e.g. if you select Frost and Forest Biome, it will paint only where _neither_ of them are present).

**Comment by Captain-Chaos** [comment]
I uploaded a snapshot with a first implementation of this. Could you guys take a look and give feedback? Checkboxes would make sense but are technically hard to do so I did it another way, with a "add another" menu option to add an item to the current filter. I'm thinking of changing that to holding the Shift key while making a selection or something like that.

Here is a download link: https://www.worldpainter.net/files/worldpainter_2.21.2-SNAPSHOT.exe. You can change it in the usual way for other platforms if desired.

**Comment by PlasticTasticc** [comment]
Thanks! I'll take a look tomorrow when I get back to my computer and let
you know what I think! 😁

**Comment by Captain-Chaos** [comment]
Could you also take a look, @Fornad95 ?

**Comment by Captain-Chaos** [comment]
Guys?

**Comment by PlasticTasticc** [comment]
Apologies for the wait, I had a medical emergency Monday and was pretty much out of commission until today. 

It seems rather nice at first glance, but the "only on" multiple options doesn't seem to work. Furthermore, if i need to do something quickly i'd ideally want to just keep on adding another and another block/mask with the eyedropper tool. but it's somewhat difficult as i'd have to carefully navigate to the option each time, and sometimes the popup menu doesn't open in the same location as before. I also tried the "except on" and that seemed to work fine, although if thats the only thing that'll work it seems kinda annoying to have to make a selection so finnicky... and what if i accidentally select the wrong block for an additional mask? Then ill have to go select all the blocks again seperately one at a time, popup after popup. This is why i suggested the checkbox in the first place. Of course, this is better than nothing, but it could still be much better imo.

**Comment by Fornad95** [comment]
I can confirm that the multiple "only on" options don't work, but that the multiple "except on" options do work.

I personally find this to already be a huge improvement to my previous workflow, so don't really have any complaints about the implementation.

**Comment by Fornad95** [comment]
@Captain-Chaos Would it be possible to implement this feature soonish?

**Comment by Captain-Chaos** [comment]
This will be in the next release (unannounced). Please test it well and let me know of any problems. I'll keep looking into ways to make it easier to use, but as you may know I'm currently not able to spend much time on the project so that may take a while.

**Comment by PlasticTasticc** [comment]
> but as you may know I'm currently not able to spend much time on the project so that may take a while.
oh I wasn't aware, thanks for remembering us in that case! hope you get the time for whichever you wanna do! :-)
