### ISSUE TITLE
Image Overlay Scale Precision

### ISSUE THREAD

**Issue by n8bar** [Captain-Chaos/WorldPainter#287]
I wish I could use decimal percentages when setting the scale of Image Overlays. For example 23% is inaccurately too small and 24% much too big because there is a drastic difference between a single percent on large images. I can get around this by scaling the image in another program but it can get quite tedious when I'm trying to be precise. I'm thinking two decimal places would do the trick.

**Comment by Captain-Chaos** [comment]
This has been implemented in version 2.16.0.
