### ISSUE TITLE
Minimum in Map Format can't be changed (saved)

### ISSUE THREAD

**Issue by MattiBorchers** [Captain-Chaos/WorldPainter#288]
I tried to change the minimum height for a 1.18 or 1.19 map, but the window wont let me click "OK" after changing just the minimum height.
When changing the minimum and maximum height, I can save and close the window, but the value wont be saved. It will stay at -64.
![minimum](https://user-images.githubusercontent.com/47185281/204595646-f5effbf0-9c70-478b-abb6-170432f82080.png)

In addition to this, it is not possible to set the minimum height when creating a new world.

Maybe it is kind of related to Issue https://github.com/Captain-Chaos/WorldPainter/issues/278, but still different.

Greetings,
Matti

**Comment by Captain-Chaos** [comment]
Hmmm. The minimum height limit is tied to the map format and can't be changed. So that explains why it stays at -64. The bug is that you are able to change it to zero. I'll look into it!

**Comment by Captain-Chaos** [comment]
I'll have to do some more investigation. I don't really remember how I intended this screen to work regarding the minimum height, but I'm not sure it currently makes sense.

**Comment by Captain-Chaos** [comment]
Why would you want to set the minimum height limit to 0?

**Comment by MattiBorchers** [comment]
> Why would you want to set the minimum height limit to 0?

It is possible to set the minimum height to 0 using a datapack ("min_y": 0).
This is useful when using ViaVersion to support players from older Minecraft versions.

**Comment by Captain-Chaos** [comment]
Yeah that amounts to the same thing as #278, which is not trivial as I said. Meanwhile I'll "fix" this one by disallowing setting the minimum height to something different than the map format's native one.
