### ISSUE TITLE
Contribution to improve Dark GUI

### ISSUE THREAD

**Issue by almic** [Captain-Chaos/WorldPainter#289]
From what I can see, you have most recently worked on improving the GUI for dark modes in commit 9344d5a076c82d99a97500ad8cfc66b83c6f68ef, which is great. Although, I can see there is still more work to be done. The main thing I noticed was that many icons which are black don't fit well into either available dark color schemes.

But, this isn't so much me asking you to do it, I'm asking if you would accept a contribution that brings the dark schemes to a more complete state. I'm already working on recoloring the icons that need the improvement the most, matching them visually to the two available dark themes so they will be appealing in either selection.

I've already looked around in the code, and noticed this change would require some code modifications to support loading more variants of icons. Some places statically load them without regard for the theme, for instance:

https://github.com/Captain-Chaos/WorldPainter/blob/6a24f777be22cac7a566faa88c2b77c430a376ea/WorldPainter/WPGUI/src/main/java/org/pepsoft/worldpainter/Palette.java#L163-L165

These would need to be moved away and loaded here instead, along with everywhere else that uses the default black icons:

https://github.com/Captain-Chaos/WorldPainter/blob/6a24f777be22cac7a566faa88c2b77c430a376ea/WorldPainter/WPGUI/src/main/java/org/pepsoft/worldpainter/Main.java#L451-L458

It might even be most appropriate to push everything related to icons and coloring in a class that defines colors and icons per theme, rather than having multiple classes managing the colors individually themselves. This way, all GUI theming can be better constrained to a single location, which would make it easier to modify in the future.

Again, I'm just wondering if this is a contribution you would accept. Regardless of the answer, though, I have already started work on producing recolored icons for the most needed. Should you want to do it yourself, hopefully you can make use of the icons I produce. Specifically, the black icons with off-white shadows, which do not look appropriate for either dark color themes. My goal is to make a set for Dark Metal and Dark Nimbus separately, because metal is significantly darker and requires a white icon set, while nimbus is grey and benefits most from an improved black icon set.

**Comment by Captain-Chaos** [comment]
I appreciate the effort! I'll take a look, there's a good chance I'll use the icons. I'll probably prefer to write the code myself. If I do it'll be something quick and dirty. The current UI is very old and I don't think it makes sense to put too much effort into it. I would rather overhaul the entire UI at some point, and move to vector based icons that can be continuously scaled, and do proper i18n at the same time so it can be translated.

**Comment by Captain-Chaos** [comment]
How would you like to be credited if I use your icons?

**Comment by Captain-Chaos** [comment]
I added some simple icon theming support: https://github.com/Captain-Chaos/WorldPainter/tree/dark-icons

**Comment by Captain-Chaos** [comment]
I decided to include this. Why not make the UI look as good as it can? I didn't inspect all the icons closely though; are they good to go?

**Comment by almic** [comment]
Apologies for responding so late to you, as far as I know these icons are ready to be dropped in as-is, I made sure they were all the same dimensions. Even the icons that aren't used at all got "dark" versions. Credit me however you usually would, which I suppose is just on the website. If you ever do a UI overhaul I would like to help, although I would argue to use a different library, perhaps one a little more open-source.

**Comment by almic** [comment]
Oh, one more thing. I don't know if you just haven't done so yet but plan to, anyway, I linked a spot where some icons are loaded statically without regard for the theme in my original post. Just wanted to be sure those were integrated into the theme, unless I'm wrong and those are just leftovers from some old commit and aren't actually used in UI.

**Comment by Captain-Chaos** [comment]
> Oh, one more thing. I don't know if you just haven't done so yet but plan to, anyway, I linked a spot where some icons are loaded statically without regard for the theme in my original post. Just wanted to be sure those were integrated into the theme, unless I'm wrong and those are just leftovers from some old commit and aren't actually used in UI.

Yeah I fixed those.

**Comment by Captain-Chaos** [comment]
I just merged this to master and it will be in the next release. Thank you very much for your contribution! 😀👍
