### ISSUE TITLE
error: unreported exception UnloadableWorldException

### ISSUE THREAD

**Issue by Geph** [Captain-Chaos/WorldPainter#290]
I'm getting a "error: unreported exception UnloadableWorldException; must be caught or declared to be thrown" when running the latest version. Traces back to ExpertPerformanceTester.java line 27 even with -DskipTests=true 

```
final WorldIO worldIO = new WorldIO();
        worldIO.load(new FileInputStream(args[0]));
        final World2 world = worldIO.getWorld();
        for (int i = 0; i < Terrain.CUSTOM_TERRAIN_COUNT; i++) {
            MixedMaterial material = world.getMixedMaterial(i);
            Terrain.setCustomMaterial(i, material);
        }
```

I'm able to run an older version (2.7.17) from last year without issue so I'm guessing it's not my system configuration?

**Comment by Geph** [comment]
I'm not sure. It fails out on building WPCore when running the mvn install -DskipTests=true
```
[INFO] Reactor Summary for WorldPainter 2.15.15-SNAPSHOT:
[INFO]
[INFO] WorldPainter ....................................... SUCCESS [  0.154 s]
[INFO] WPUtils ............................................ SUCCESS [  0.394 s]
[INFO] WPCore ............................................. FAILURE [  1.661 s]
[INFO] WPDynmapPreviewer .................................. SKIPPED
[INFO] WPJava9Support ..................................... SKIPPED
[INFO] WPGUI .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.255 s
[INFO] Finished at: 2022-12-06T13:48:30-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project WPCore: Compilation failure
[ERROR] C:\Users\Geph\IdeaProjects\WorldPainter-2023\WorldPainter\WPCore\src\test\java\org\pepsoft\worldpainter\ExportPerformanceTester.java:[27,20] error: unreported exception UnloadableWorldException; must be caught or declared to be thrown
```
I tried individually building the remaining components and WPJava9Support works but not Dynmap or the GUI.  I'm pretty sure I got the pre-req setup right but it's possible I borked something up. I can try on a Macbook and see if it's any different if that might help?

**Comment by Captain-Chaos** [comment]
Ah you're _building_ WorldPainter. You said running, hence my confusion. 😉

I see now that there is indeed a checked exception declaration missing. It happened because I fixed an exception that _should_ have been a checked exception, but wasn't. For some reason I can't explain my IDE didn't catch this error and happily continued compiling the code base. I'll update it. Thanks for the heads up.

**Comment by Geph** [comment]
Thanks! Sorry poor word choice on my part. We're working on making a version for kids to make exoplanets for this project, in case you're curious -> https://whimcproject.web.illinois.edu

**Comment by Captain-Chaos** [comment]
It's fortunate that you are using Java Edition rather than Education Edition! Education Edition is Bedrock and doesn't work with WorldPainter.
