### ISSUE TITLE
[ERROR] Failed to execute goal on project WPDynmapPreviewer: Could not resolve dependencies for project org.pepsoft.worldpainter:WPDynmapPreviewer

### ISSUE THREAD

**Issue by Geph** [Captain-Chaos/WorldPainter#291]
Sorry to bug you again! I appreciate you fixing the dependency issues earlier. While I'm now able to compile WPCore there seems to be a WPDynmapPreviewer dependency issue during the build process. I've tried both the latest (2.15.15) release and a regular past release (2.15.13), the error is the same. 

```
[INFO] Reactor Summary for WorldPainter 2.15.13:
[INFO]
[INFO] WorldPainter ....................................... SUCCESS [  0.163 s]
[INFO] WPUtils ............................................ SUCCESS [  0.394 s]
[INFO] WPCore ............................................. SUCCESS [  0.780 s]
[INFO] WPDynmapPreviewer .................................. FAILURE [  0.008 s]
[INFO] WPJava9Support ..................................... SKIPPED
[INFO] WPGUI .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.397 s
[INFO] Finished at: 2022-12-06T16:35:01-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project WPDynmapPreviewer: Could not resolve dependencies for project org.pepsoft.worldpainter:WPDynmapPreviewer:jar:2.15.13: Failed to collect dependencies at us.dynmap:DynmapCore:jar:3.4: Failed to read artifact descriptor for us.dynmap:DynmapCore:jar:3.4: us.dynmap:dynmap:pom:3.4 was not found in https://www.worldpainter.net/maven-repo/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of worldpainter-private has elapsed or updates are forced -> [Help 1]
```
I did try to adjust the version call in pom.xml in DynmapPreviewer but older versions (2.3-snapshot etc) didn't seem to work, nor did adjusting any tags (classifier, scope provided, etc). I'm pretty new to all this stuff but I imagine it's an easy fix.

**Comment by Captain-Chaos** [comment]
I don't know why that would be. The pom is there: https://www.worldpainter.net/maven-repo/us/dynmap/DynmapCore/3.4/DynmapCore-3.4.pom and the jar as well: https://www.worldpainter.net/maven-repo/us/dynmap/DynmapCore/3.4/DynmapCore-3.4.jar. It should work.

Try downloading those files manually and installing them in your local repo using [`mvn install:install-file`](https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html).

You might have to do the same for other dependencies from that repo.

**Comment by Captain-Chaos** [comment]
Although this is making me thing the problem may be something else: `us.dynmap:dynmap:pom:3.4 was not found`. _That_ pom belongs to Dynmap and is not in my repo. I'll look into it.

**Comment by Captain-Chaos** [comment]
OK, it looks like Mike Primm doesn't publish that pom, so I've added it to the WorldPainter private repo as well. Could you try again? You may have to use the `-U` option to force Maven to re-check the remote repo.

**Comment by Geph** [comment]
Got it - thank you!
```
[INFO] Reactor Summary for WorldPainter 2.15.15-SNAPSHOT:
[INFO] 
[INFO] WorldPainter ....................................... SUCCESS [  0.192 s]
[INFO] WPUtils ............................................ SUCCESS [  0.623 s]
[INFO] WPCore ............................................. SUCCESS [  0.836 s]
[INFO] WPDynmapPreviewer .................................. SUCCESS [  4.916 s]
[INFO] WPJava9Support ..................................... SUCCESS [  0.111 s]
[INFO] WPGUI .............................................. SUCCESS [  4.119 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```
