### ISSUE TITLE
Feature request: More colour/texture/transparency options

### ISSUE THREAD

**Issue by Fornad95** [Captain-Chaos/WorldPainter#295]
Based on these two requests:

https://www.reddit.com/r/Worldpainter/comments/vzfu98/i_love_world_painter/
https://www.reddit.com/r/Worldpainter/comments/10qiaom/feature_request_biome_display_editor/

Add the ability to customise the texture and transparency of custom layers, as well as the texture, colour and transparency of biome layers. This would help users distinguish between their layers better, and also give them a wider range of options for map appearance.

**Comment by Dannypan** [comment]
Seconding this. Right now painting biomes, especially oceans/rivers, is impractical as they're all the same colour. It would also really help people with colour blindness to have high contrast between biome layers.

**Comment by Captain-Chaos** [comment]
This was partially implemented in release 2.20.0. I'll see how feasible it is to do this for biomes also.

**Comment by Captain-Chaos** [comment]
The next release will also support this for custom biomes. For technical reasons it's harder to do for vanilla biomes, and that also makes less sense I think. I have made them a little more distinctive in the next release. If that still remains desirable after this is released feel free to file a new feature request.
