### ISSUE TITLE
Script Api - get absolute path to current script file

### ISSUE THREAD

**Issue by NeumimTo** [Captain-Chaos/WorldPainter#297]
Im working on a script that dumps data out of current wp dimension. I want to create a file in a same directory, from which the js script was loaded. This is currently not possible.

Since nashorn already supports extension properties like `__LINE__, __FILE__, __DIR__`, my suggestion would be to create similar extension "`__SCRIPTPATH__`"

**Comment by Captain-Chaos** [comment]
Yeah this makes sense. Overriding `__DIR__` (which should already contain this, but apparently doesn't) does not seem to work, but I will add a global `scriptDir` variable in the next release which will contain the full path of the directory in which the script file is contained.
