### ISSUE TITLE
Cannot place custom ground cover layer, custom objects on snow block or deep snow

### ISSUE THREAD

**Issue by JamesRon** [Captain-Chaos/WorldPainter#299]
MC version: 1.19.2
WP version: latest release as of 2/20/2023

I am unable to place my custom ground cover layer (basically using the sphere brush with a high thickness and block type as barrier to achieve an invisible map boundary) on "snow block" or "deep snow" block types. Frost or "snow" does not seem to be the issue.

It appears as though custom ground cover, object layer and plant layers cannot be applied to these 2 blocks. It appears in the GUI like it will export but on export it just cuts off over any block that is deep snow or snow block.

**Comment by Captain-Chaos** [comment]
This is as designed. Snow does not count as a solid foundation; it counts as "air". The custom ground cover layer does not place blocks when they would be floating on air, as that it is the behaviour most users would usually expect. The custom objects layer does place objects floating on air, but only if you select that option in the object settings.
