### ISSUE TITLE
Feature Request: Have the representation of the terrain in 3D View stay true to toggled layers in normal view.

### ISSUE THREAD

**Issue by PlasticTasticc** [Captain-Chaos/WorldPainter#311]
Currently i use a lot of layers for worldpainter worlds, reason being I have a lot of masks I export from worldmachine. But because the 3D View shows everything no matter how many masks I have toggled in the actual overview, I very rarely if ever really use the 3D view. I would just like the 3D View to stay faithful to the layers/annotations I have toggled at any given time.

**Comment by Fornad95** [comment]
Seconded, this would be great
