### ISSUE TITLE
Feature Request: Option to keep current terrain when importing new heightmap.

### ISSUE THREAD

**Issue by PlasticTasticc** [Captain-Chaos/WorldPainter#312]
Essentially just that. As it currently stands the only way I see of keeping the current terrain (ie: the blocks already painted into the map) Is to import the new heightmap as a brush. Whereas I would like to be able to import a heightmap into the current dimension, without applying a theme. So i may have already painted a map with grey concrete, yellow stained glass and cobwebs. And when importing a new heightmap into that dimension the blocks stay in the exact same place as they were before, only the height being overwritten.

**Comment by Captain-Chaos** [comment]
It's not entirely clear but I assume you're already talking about the Edit -> Import -> Height map into current dimension... functionality (and not File -> Import new World -> From height map...). I see what you mean, I can easily add an option there to leave the terrain type alone. It will be in the next release.

**Comment by PlasticTasticc** [comment]
> It's not entirely clear but I assume you're already talking about the Edit -> Import -> Height map into current dimension... functionality (and not File -> Import new World -> From height map...). I see what you mean, I can easily add an option there to leave the terrain type alone. It will be in the next release.

Yes, apologies for the lack of clarification, that was exactly what I meant! Thank you!
