### ISSUE TITLE
[bug] Crimson and Warped stems not categorised as logs. Custom trees with leaves on them decay despite selecting not to decay.

### ISSUE THREAD

**Issue by Ratchet97** [Captain-Chaos/WorldPainter#316]
Hello, I made custom trees with crimson and warped stems combined with leaves and when making a custom object layer I selected leaves to decay. When I opened the world with the trees in them they started to decay when they shouldn't. I tried then making the schematics again but this time I made sure I made the leaves not persist with world edit and then made a custom object layer with it. World edit recognized the leaves decay so I did not have to set it and made sure the schematic behaved as exported. I went to the world and behold leaves decayed once again. Then I tried to paste the schematic manually and leaves did not start to decay and when I broke the logs leaves behaved as normal where not being connected to log began to decay. As it should be. Mind you as unusual this might sound leaves really should not decay on crimson and warped logs. I tested this with naturally gown oaks where I placed stem next to leaves and cut the oak tree if the leaves decay. This is also not a world edit issue as I asked world edit devs if the data for leaves is properly saved. It is as they confirmed it to me.

Here I am enclosing the schematic of a custom tree with crimson stem and flowering azalea leaves (any leaf block works really I just happened to have azalea). To reproduce create a custom object layer with this and have world edit installed for placing the schematic for testing purposes.
[crimson_custom_tree_schematic.zip](https://github.com/Captain-Chaos/WorldPainter/files/11580375/crimson_custom_tree_schematic.zip)

Screenshot of the custom tree placed in the world where it leaves decayed:
![image1654](https://github.com/Captain-Chaos/WorldPainter/assets/48301568/2f6f899d-b511-46b1-9982-eef658b6b61f)
For some very odd reason the ones you see stayed there and did not decay, rest did.

Screenshot how it looks like as whole:
![image11](https://github.com/Captain-Chaos/WorldPainter/assets/48301568/3678fcd2-7006-42ec-813b-f8acd43eb1c5)

A member of world painter discord server sijmen_v_b mentioned this could be that world painter does not recognize crimson and warped stems as logs therefore I put it in title. Seems like plausible thing. Maybe even flowering azalea and normal azalea leaves might be causing this?

Thank you for considering my report and I hope this devs find a solution for this issue soon enough. I really want my custom trees on the map and don't feel like setting them as not to decay. Players will play survival mode on this one.

**Comment by Ratchet97** [comment]
I "fixed" this issue with the crimson and warped trees by unchecking calculate distance properly for leaves in post processing tab.

**Comment by Captain-Chaos** [comment]
For warped and crimson trees WorldPainter considers the _hyphea blocks the "logs". Does Minecraft also consider the _stem blocks "logs"? I.e. do leaves not decay in Minecraft f you replace the wood log blocks with crimson or warped stem blocks?

**Comment by Captain-Chaos** [comment]
Never mind; I see what's going on I think. This will be fixed in the next release.
