### ISSUE TITLE
More scripting support

### ISSUE THREAD

**Issue by creativitRy** [Captain-Chaos/WorldPainter#32]
Hi Captain. Thank you for the new script descriptor stuff. If you have time, could you work on these scripting features?
- Drop down lists - when you have to select one from a list of values
- Material drop down lists - being able to select a block type or custom material
- Layer drop down lists - being able to select a layer - maybe an option to only select from on-off layers or 8-bit layers
- Biome selection thingy - either a simple drop down list or a fully fleshed out version like the biome panel in the main app
- Text area - for inputting strings with multiple newlines
- Label - uneditable string - a default string of null would act as a separator
- If the default value of a file is set, ability to show the file chooser starting in the default value
- Ability to set the default text in the original parameters box
- Allowed number range for integers and floats
- Ability to specify allowed file extensions when selecting a file

Thank you!

**Comment by Captain-Chaos** [comment]
Would you mind splitting these up into separate requests for enhancements? Having them all in one issue isn't very useful as it makes it impossible to track and manage them separately. I'm closing this issue for that reason; feel free to resubmit your ideas as separate issues.

Also it's only fair to tell you that I'm not likely to implement any of these any time soon. The scripting support is meant to be rudimentary, with just enough barebones features to be able to function. It's too niche and advanced to put a lot of time into QoL features such as these. I hope you understand!
