### ISSUE TITLE
[Bug]Half plants (such as sunflowers) filtering does not affect chunks located on the coordinate axis.

### ISSUE THREAD

**Issue by ALingll** [Captain-Chaos/WorldPainter#320]
``Since I found the probelm that schematics with half double tall plants would not export correctly in #306 ,I have done some further tests and have also examined the relevant code. I found two probems below.

Firstly, Post-processing filters for this type of plant will not affect chunks located on the coordinate axis. Here are the screenshots of my test results. The second image is from a more extreme test.
![image](https://github.com/Captain-Chaos/WorldPainter/assets/123755160/3eaab6fe-efa9-4b0e-ae8b-f07aca846122)
![image](https://github.com/Captain-Chaos/WorldPainter/assets/123755160/a0358f53-2417-450c-82aa-3476ce5ac16f)
![image](https://github.com/Captain-Chaos/WorldPainter/assets/123755160/054870c7-d841-4807-8061-488ef2c536ba)
![image](https://github.com/Captain-Chaos/WorldPainter/assets/123755160/1f417915-b6c1-4d8a-b7d7-5cb96ceed584)

Secondly, upon examining the code in `WorldPainter-master\WorldPainter\WPCore\src\main\java\org\pepsoft\worldpainter\platforms\Java1_15PostProcessor.java`, I found that there are no conditional checks for filtering high plants. This means that the filtering in this section is unconditionally executed and not influenced by any post-processing options.I believe it would be appropriate to add a checkbox option in the post-processing settings to control whether this filtering should be executed. Alternatively, I think it could even be included directly in the code block that filters floating plants. After all, if we allow plants to float, why not allow partially half plants to remain as well? If the existence of half plants can be made legitimate, it would greatly facilitate creators in their artistic endeavors and the use of such blocks, allowing for a more vibrant display of creativity.
```
                            case MC_SUNFLOWER:
                            case MC_LILAC:
                            case MC_TALL_GRASS:
                            case MC_LARGE_FERN:
                            case MC_ROSE_BUSH:
                            case MC_PEONY:
                                if ("lower".equals(material.getProperty(HALF))) {
                                    // Lower half of double high plant; check there's grass or dirt below
                                    if ((! materialBelow.modded) && materialBelow.isNotNamedOneOf(MC_GRASS_BLOCK, MC_DIRT, MC_COARSE_DIRT, MC_PODZOL, MC_FARMLAND, MC_ROOTED_DIRT, MC_MOSS_BLOCK, MC_MUD)) {
                                        // Double high plants can (presumably) only exist on grass or dirt // TODO: check
                                        // The upper block will be removed below in the next iteration
                                        material = clearBlock(minecraftWorld, x, y, z);
                                    }
                                }
                                break;
```
```
                    if (material.vegetation && material.isPropertySet(MC_HALF)) {
                        // Check that all lower and upper halves of plants have their corresponding opposite half
                        if ("upper".equals(material.getProperty(HALF))) {
                            if (materialBelow.isNotNamedSameAs(material) || (! materialBelow.isPropertySet(MC_HALF)) || (! "lower".equals(materialBelow.getProperty(HALF)))) {
                                material = clearBlock(minecraftWorld, x, y, z);
                            }
                        } else {
                            if (materialAbove.isNotNamedSameAs(material) || (! materialAbove.isPropertySet(MC_HALF)) || (! "upper".equals(materialAbove.getProperty(HALF)))) {
                                material = clearBlock(minecraftWorld, x, y, z);
                            }
                        }
                    }


```

**Comment by Captain-Chaos** [comment]
Can you send me the .world file for that extreme test?

**Comment by ALingll** [comment]
[testHalf.zip](https://github.com/Captain-Chaos/WorldPainter/files/11817484/testHalf.zip)
