### ISSUE TITLE
Can't add immersive petroleum crude oil deposits and can't add any other modded blocks make it so I can add mods from curseforge and it imports world gen from mod please

### ISSUE THREAD

**Issue by zachary234533532353335533461113466** [Captain-Chaos/WorldPainter#322]

**Comment by Captain-Chaos** [comment]
Sorry, but this is unintelligible. Can you please shorten the title and provide an actual description, giving some useful details about what you are asking for. You _can_ add mod blocks already, and I don't know what "import world gen from mod" means.

**Comment by zachary234533532353335533461113466** [comment]
How do you do mod blocks> description

**Comment by zachary234533532353335533461113466** [comment]
Sorry I didn't know my apologies and kudos you responded very formally

**Comment by Captain-Chaos** [comment]
OK, so this is not a support forum, this is a place to report bugs and request features. If you're just asking how to do things there are other places for that:

- The official support subreddit: https://www.reddit.com/r/Worldpainter/
- The unofficial Discord: https://discord.gg/NrGWtXnra8
- The FAQ: https://www.worldpainter.net/trac/wiki/FAQ and troubleshooting guide: https://www.worldpainter.net/trac/wiki/Troubleshooting

In short, to use mod blocks, there are several ways. You can create Custom Object layers with schematics with mod blocks in them. You can create Custom Terrain types, Ground Cover layers or Underground Pockets layers with custom materials. You have to know the mod namespace and the block name, but then you can specify any modded block wherever you can choose a block type by typing in the right names.

I can't help you with what those names are for Immersive Petroleum mod though; you'll have to find that out from the documentation or the authors. But as an example for Conquest Reforged, if you wanted to add slate rocks you would set the first field to "conquest" and the second field to "slate_rocks".

I'll close this ticket now.
