### ISSUE TITLE
Feature request: Re-order layers within palettes

### ISSUE THREAD

**Issue by Fornad95** [Captain-Chaos/WorldPainter#326]
As per the request here:

https://www.reddit.com/r/Worldpainter/comments/14ilsve/custom_layers_order_randomised_in_latest_update/

The ability to manually re-order layers within their palettes would be a very useful organisation feature.

**Comment by Dannypan** [comment]
Seconding this. All my layers are out of order now. I put them back in order in a new palette and they’re out of order again. 

I’d also like to request the ability to rename palettes without having to make new ones, and the highly requested scroll bar function for them please.

**Comment by PlasticTasticc** [comment]
Holy heck yes!!! This would be such a godsend!

**Comment by Captain-Chaos** [comment]
Drag and drop would be significantly more complex to implement, but in the next release it will be possible to re-order (and rename) palettes using a list.
