### ISSUE TITLE
Import Mask Issue

### ISSUE THREAD

**Issue by CaliberMC** [Captain-Chaos/WorldPainter#329]
When using the Import -> Mask as Terrain or Layer and choosing and choosing annotations, the color selected does not appear.  Instead it uses the next color.  Seems to be and OBO error as it always selects one higher color.

Edit: Some of the colors actually do show up correctly.  The Cyan, Green and Red definitely bump up by one though.

**Comment by Captain-Chaos** [comment]
I'll look into it. It's slightly complicated because Annotations do not actually exist for all wool colours ("gray"/data value 7 is missing) so the layer values do not map 1:1 onto colour IDs in Minecraft.

**Comment by Captain-Chaos** [comment]
It seems that it is only the colour names in the drop-down that are incorrect; not the colours. Can you confirm that?
