### ISSUE TITLE
[Feature request] Custom annotation layers

### ISSUE THREAD

**Issue by Dannypan** [Captain-Chaos/WorldPainter#333]
The annotation layers have their uses but could be adjusted to allow for better map editing via custom annotations:

- Custom annotation colours can be anything on the RGB spectrum (they would not be exported as wool),
- Allow for transparency to see terrain underneath,
- Can be moved to different palettes depending on use.

Right now if I want to make masks instead of using an annotation (as you can do all of the above), I have to make custom object layers and then disable them. It's an awkward process and the "you've got x layers disabled" is frustrating when doing a lot of text exports (not to mention it's slower each time I add one of these layers to my project). 

I think a custom annotation feature would help us worldpainters, especially for bigger projects.

**Comment by PlasticTasticc** [comment]
I've been using your method for years now, and can confirm custom annotation layers would be amazing. The way I've done it though where my way might differ from yours is that I've just used a schematic of 1 block of air, and then had the block spacing set to like a million or some high number like that. But man would customizable annotation layers help much more!!

**Comment by Captain-Chaos** [comment]
This will be in the next release.

**Comment by Dannypan** [comment]
Amazing, thank you!
