### ISSUE TITLE
Test export/map import preview not working as of 2.21.0

### ISSUE THREAD

**Issue by Dannypan** [Captain-Chaos/WorldPainter#350]
When attempting to test export it shows as having no tiles:

![image](https://github.com/Captain-Chaos/WorldPainter/assets/39864044/bca15398-7ccb-4d1c-b269-d1558ce43c41)

and when attempting to import a height map in WorldPainter, the box is grey:

![image](https://github.com/Captain-Chaos/WorldPainter/assets/39864044/6185656e-8d39-43d2-b8ce-5f843da246cf)

**Comment by Captain-Chaos** [comment]
This will be fixed in the next release.
