### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Fel1xxxxx** [Captain-Chaos/WorldPainter#353]
Im creating 70000x70000 blocks world and i dont understand why it eats all my 32gb of RAM and asking for more.

And i want to ask: Is there any point in waiting for the creation of the world after this message or can I close the program, as it continues to eat 22-30 gigabytes of memory?

**Comment by Captain-Chaos** [comment]
There is no point in waiting, no. The process has crashed; that's why it gives the error message. 70000 blocks squared is gigantic; it's not strange that that would use a lot of memory, although I would have thought that 32 GB would be enough. Are you sure it is actually using all of that? What is the "maximum configured memory" on the Tech Info tab of the About screen?

**Comment by Fel1xxxxx** [comment]
> There is no point in waiting, no. The process has crashed; that's why it gives the error message. 70000 blocks squared is gigantic; it's not strange that that would use a lot of memory, although I would have thought that 32 GB would be enough. Are you sure it is actually using all of that? What is the "maximum configured memory" on the Tech Info tab of the About screen?

WorldPainter version: 2.21.1 (20230821215634)
Java version: 17.0.7
Operating system: Windows 11 amd64 (version 10.0)
WorldPainter config directory: C:\Users\User\AppData\Roaming\WorldPainter
Installation ID: fa309072-aa40-44b2-abc4-a8afded223cc
Minecraft data directory: C:\Users\User\AppData\Roaming\.minecraft
Available CPU cores: 16
**Maximum configured memory: 30,560 MB**
Currently allocated memory: 912 MB

**Comment by Fel1xxxxx** [comment]
I tried to generate different worlds and realized that worlds up to 50 thousand are generated without problems (if you do not take into account the fact that after their generation the memory is still 20+ gigabytes and even when you close the program the memory remains 10-12 gigabytes full)

**Comment by Captain-Chaos** [comment]
I'm going to close this as I don't see a bug. You are just trying to create a larger map than will fit in memory. 70,000 blocks squared is 4,900,000,000 blocks. With 32 GB that leaves just seven bytes per block. It stands to reason that that is not enough. You'll have to install more memory if you want to work on such a gigantic map, although I _very_ strongly advise against as it will take you a decade to complete.
