### ISSUE TITLE
Unable to "copy existing" layers in a custom cave layer

### ISSUE THREAD

**Issue by Dannypan** [Captain-Chaos/WorldPainter#355]
Whenever I try to copy an existing layer into the floor/roof layers tab in a custom cave layer an error pop up appears:

Type: java.lang.NullPointerException
Message: null

Full details:

java.lang.NullPointerException: null
	at java.lang.Class.isAssignableFrom(Class.java:-2)
	at org.pepsoft.worldpainter.layers.tunnel.TunnelLayerDialog.lambda$addLayer$5(TunnelLayerDialog.java:466)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.pepsoft.worldpainter.layers.tunnel.TunnelLayerDialog.addLayer(TunnelLayerDialog.java:467)

WorldPainter version: 2.21.1 (20230821215634)

java.version: 17.0.7
java.vendor: Oracle Corporation
java.vm.version: 17.0.7+8-LTS-224
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 11
os.arch: amd64
os.version: 10.0
user.home: C:\Users\Reception
user.dir: C:\Program Files\WorldPainter
user.country: GB
user.language: en

Free memory: 1977382152 bytes
Total memory size: 6098518016 bytes
Max memory size: 14839447552 bytes

World name: Gleamora Mountains
Platform: Minecraft 1.19 or later (org.pepsoft.anvil.1.19)
Seed: -6796614952090148858
Bounds: -56, -56 => 55, 55
Height: 512
Number of tiles: 12544
Layers in use: Ta - Eurasian Aspen (Z), Al - Eurasian Aspen (Z), Mask 2 - Skyrim Cold, Mask 3 - Autumn Taiga, Basalt Pillars, Ta - Dead Coastal Fir (Zr), Bo - Dark Stone Boulder, Autumn Taiga Forest, Ta - Serbian Spruce (Z), Pass A, Ta - Taller Spruce (S), Biome, Al - Coastal Fir (Zr), Ta - Balsam Fir (L), Large Ice Spike (NE), Sp - Snowy Ice Thorns, Mask 4 - Central Ridge, Ta - Larch (Z), Skyrim Mtn Pass, Large Ice Spike (E), Ta - Japanese Pine (Z), Ta - Norway Spruce (Z), Al - Mountain Ash (Zr), Lava, Ta - Scots Elm (Z), Ta - Japanese Cedar (Z), Large Ice Spike (SW), Frost, Sp - Ice Spire Cluster, Autumn Taiga Mix, Mask 5 - Volcano Ridge, Skyrim Path, Ta - Tibetan Juniper (Z), Large Ice Spike (W), Ta - Small/Med Spruce (S), Ta - Siberian Spruce (Z), Snow, Ta - Scots Pine (Z), Mask 1 - Skyrim Inspired, Pass B, Ta - Swiss Pine (Z), Ta - Dahurian Larch (Z), Ta - Lodgepole Pine (L), Ta - Giant Sequioa (Zr)
Border: null @ 62
Sub surface material: Stone Mix
Water height: 62

Operation: Spawn
Radius: 702
Brush: Constant Square (radius=702, brushShape=SQUARE, level=0.51)/org.pepsoft.worldpainter.brushes.BitmapBrush@5ccd90c5
Level: 0.51/1.0
Zoom: -1
Hidden layers: [Biome]

**Comment by Dannypan** [comment]
Latest version of WorldPainter btw.

**Comment by Captain-Chaos** [comment]
Found the bug. It's triggered by having custom annotation layers. This will be fixed in the next release.
