### ISSUE TITLE
Heightmap export for 16bit png is broken

### ISSUE THREAD

**Issue by IR0NSIGHT** [Captain-Chaos/WorldPainter#376]
WHEN i have a mountain that is higher than 255
AND i use "export low res image" in the export window
THEN the exported image has no color values
every pixel has value zero (check in program)

export works fine for 8bit images below 255 height

attached exported 16bit png from world 
happens on 2.22.1 and latest update too

![generatedworld_heightmap](https://github.com/Captain-Chaos/WorldPainter/assets/32139214/c7af29fb-6c0b-478a-870e-9e920ae8c19a)
![generatedworld](https://github.com/Captain-Chaos/WorldPainter/assets/32139214/4b432f4c-55e6-4549-9497-46ce0ff80c4c)

**Comment by Captain-Chaos** [comment]
It does have colour values. Try importing that first image as a height map in WorldPainter. I just looks dark because the values are low compared to the maximum possible value. Check out this [FAQ](https://www.worldpainter.net/trac/wiki/FAQ#Whyismyexportedheightmapentirelyblack).
