### ISSUE TITLE
World not generating

### ISSUE THREAD

**Issue by dreadstrike-inferniclaw** [Captain-Chaos/WorldPainter#392]
So im trying to make a 750k by 650k world for my mc server but its not generating
i have 100 gb allocated to worldpainter
but it just freezes

**Comment by Captain-Chaos** [comment]
Is that a typo, or are you really trying to create a 750,000 by 650,000 blocks map? If so then that is _insanely_ large. That is 487.5 billion blocks, even at 100 GB that only leaves 4 bytes per block so it's not surprising that doesn't work.

**Comment by dreadstrike-inferniclaw** [comment]
Not a typo, have a very large world. Here's why
[static.wikia.nocookie.net/aethereya/images/3/35/Orthosmap.jpg/revision/latest?cb=20240321190452](url)

**Comment by dreadstrike-inferniclaw** [comment]
Well I think I have another hundred GB so how much would that be

**Comment by dreadstrike-inferniclaw** [comment]
@Captain-Chaos it's working now i believe. Sorry to have wasted your time.
