### ISSUE TITLE
World Painter don't import water correctly if I use map import

### ISSUE THREAD

**Issue by ErikSteiner** [Captain-Chaos/WorldPainter#41]
A while ago, I created a map with World Painter. When I was done, I used MCEdit to place some rivers, because it is very tricky to do that in World Painter, imo. When I was done, I realized that I missed some biomes at the map and so I imported the map into World Painter again. After importing the map, I noticed that my rivers were broken. They were cut into peaces, because some "water parts" were missing.

By comparing the imported map in World Painter with the actual map loaded in MCEdit, I noticed that World Painter don't import water correctly. Water still (9:0) will be loaded correctly, but if I have flowing water with different ID's than 9:0, they are not going to be imported: 9:1, 9:2, etc.

I attached some screenshots that will show the issue.
![1](https://cloud.githubusercontent.com/assets/2684018/21003997/8eae0bca-bd2e-11e6-9444-b90fcd73e9a8.jpg)
![2](https://cloud.githubusercontent.com/assets/2684018/21003998/8eae8104-bd2e-11e6-8acf-04c89ba26e77.jpg)
![3](https://cloud.githubusercontent.com/assets/2684018/21003999/8eae9fcc-bd2e-11e6-848b-ef8612558b3d.jpg)

**Comment by Captain-Chaos** [comment]
"Don't"?! ;) :p

**Comment by Captain-Chaos** [comment]
This is correct behaviour. Flowing water can't be represented in WorldPainter, so it isn't imported. However after merging the flowing water from the existing map should be merged back in, so it should not be a problem in practice. Is that not working correctly?

**Comment by ErikSteiner** [comment]
Thank you for clarification. I haven't tried the merge option yet. I always exported the map as a new map for testing. I will try to merge the map and I am going to report my experience.

I have one secondary issue. If I create a map in World Painter and I use a terrain that is not yet present in the Minecraft version that I use, will it vanish? So for example I use 1.7.10 that doesn't contain diorite and I create a map with it. Will World Painter have a look at my Minecraft version, before it will export the map?

**Comment by Captain-Chaos** [comment]
No, WorldPainter exports whatever blocks you have used. It varies what Minecraft will do if you use blocks it doesn't know about. In general I think older versions will change them to air, newer versions might crash.

It's best to take the Minecraft version you're going to use into account and not use blocks which it doesn't know about (which might mean e.g. using Stone as underground material instead of Stone Mix or Bare Grass instead of Grass on the surface).

**Comment by Captain-Chaos** [comment]
Since WP is working correctly in regards to importing water I'm closing this issue. If merging water doesn't work correctly then please feel free to file an issue for that!
