### ISSUE TITLE
Worldpainter 2.23 standard material window clears/collapses when docked

### ISSUE THREAD

**Issue by Ivain1** [Captain-Chaos/WorldPainter#427]
After installing the new update, I noticed that my terrain window had gone blank. Playing around with it, I noticed it had an extra border around it that seemed responsive to the window size, and that it was fine when floating free or docked with the majority of my custom layers.
It appears that whatever additional frame you've put the terrain in becomes tiny if it deems the space 'too small' for the standard terrain window to fit in. This goes for both horizontal and vertical space.
 Seeing as it has always fit in the space I put it in, but it now appears to demand an extra margin to not vanish, this has thrown off my normal workspace layout. 
 I doubt it's intentional, and perhaps this was even intended to counter a previous minor problem with some windows getting stuck if a lot of custom brushes or custom layers were present, but I would prefer if it were fixed.
 Image attached of where I normally place it, and what it now looks like there.
![blank terrain](https://github.com/user-attachments/assets/486567a1-33a7-4bf8-ac71-ad0c1b49f832)

**Comment by Captain-Chaos** [comment]
Hmmm. I have been working on those panels, in order to try to get them to be _more_ responsive, but nothing should have changed about their functionality yet.

My apologies. I will look into it shortly.

**Comment by Captain-Chaos** [comment]
It's only the Terrain tab which does this, right?

**Comment by Captain-Chaos** [comment]
This is fixed in version 2.23.1.

**Comment by Ivain1** [comment]
Yeah, your recent update solved all issues I was having, thank you for your
quick work.
