### ISSUE TITLE
CPU usage rises to 100% and remains there for several seconds after a large global operation

### ISSUE THREAD

**Issue by ajthemacboy** [Captain-Chaos/WorldPainter#45]
GIF of the problem: http://buildx.ml/ul/u/hcXKz7o.gif

After certain global operations on large maps, CPU usage rises to 100% for several seconds (longer depending on the size of the map.) During this time, WorldPainter is very laggy. 

My WP version is 2.3.2.

**Comment by Captain-Chaos** [comment]
Is it problematic? It's probably not a bug, just a lot of housekeeping from the large operation it just performed. Tracking down the exact cause might be hard to do.

**Comment by ajthemacboy** [comment]
It is very annoying, especially when I have to do a lot of large global operations. Or, when I do a global operation and want to pan around to see what changed. 

Plus, it didn't used to happen, so I'm guessing whatever changed to cause it to happen now isn't necessary, but I don't know.

**Comment by Captain-Chaos** [comment]
Alright, I'll look into it. Could you send me a .world file which shows the problem, and give me instructions on how to trigger it?

**Comment by ajthemacboy** [comment]
I'm having trouble replicating what I was experiencing, even using the same global operation on the same world. It must have just been a computer problem, sorry to trouble you.

**Comment by Captain-Chaos** [comment]
It could still have been caused by WorldPainter, just needing very specific conditions to be triggered. Feel free to submit an issue if it does reoccur and you can reproduce it reliably!
