### ISSUE TITLE
Editing multiple custom objects sets all their offsets to 0,0,0

### ISSUE THREAD

**Issue by creativitRy** [Captain-Chaos/WorldPainter#46]
I have a custom object with a custom offset.
![](https://i.gyazo.com/0590a26d76e2236ef5fa25636703e070.png)

If I select multiple
![](https://i.gyazo.com/f07ddaf64a1776e61fdce44b67f9a3b9.png)
and edit them,
![](https://i.gyazo.com/36b6dfa5eeaac9e788512ab46d7006c7.png)

the offsets reset back to 0, 0, 0
![](https://i.gyazo.com/c6b7fbcee4b7bc90994372fd1e864cf3.png)

**Comment by Captain-Chaos** [comment]
This is now fixed in 2.3.6. Thanks for your help! 👍
