### ISSUE TITLE
Layered material that doesn't rely on the height of the terrain

### ISSUE THREAD

**Issue by Katrix** [Captain-Chaos/WorldPainter#49]
I don't know if this is a bug, or just how it's supposed to work, but at the moment if I add a layered material that for example looks like Ice thickness 1, air thickness 3, lava thickness 1. I just get ice that is 5 thick.

**Comment by Captain-Chaos** [comment]
Sounds like a bug. Does this still happen? If so, can you attach a .world file which demonstrates the problem?

**Comment by Katrix** [comment]
![layerbug](https://user-images.githubusercontent.com/11007080/39123938-e06ca420-46f9-11e8-8f95-97fb170b97d0.png)

Here is a picture. Expected on the left, result on the right. Here is the layer itself.

[CrystalLava.zip](https://github.com/Captain-Chaos/WorldPainter/files/1937930/CrystalLava.zip)

**Comment by Captain-Chaos** [comment]
I think this is working as expected. The layers are relative to bedrock, not to the surface. If you use this as the subsurface material you will see the lava and the air at the bottom of the map. The reason you're seeing just ice is that the topmost layer is repeated upwards (and the bottom most layer downwards) if a material is not set to repeat.

Depending on what the exact result is that you are trying to achieve, you might make the lava layer a lot thicker to push it nearer to the surface. If you want the ice layer to be a specific thickness with just air above it, add an extra air layer at the top.

In the just released new version 2.5.0 of WorldPainter there is now an option in Custom Ground Cover Layers to have a layered custom material be relative to the terrain surface, or to the top of the ground cover. Take a look and see if that will allow you to achieve your desired result. Remember that you can set a negative thickness to make it dig down and replace the surface terrain.

I'll close this for now, but don't hesitate to open a new issue if you think it isn't working right, or if you want to request a new feature.
