### ISSUE TITLE
Customize beaches

### ISSUE THREAD

**Issue by Katrix** [Captain-Chaos/WorldPainter#51]
Often I find myself wanting to add something like beaches, but I can't use the WorldPainter toggle, as it might be that I want them to be made slightly differently, for example using another block. It would be nice if there was a feature that let you customize how the beaches would look like.

**Comment by Captain-Chaos** [comment]
You can do that by creating your own custom material, and then using that instead of the Beaches terrain type. If you want it just around the water line you can use the brush settings panel to limit your painting to those heights.
