### ISSUE TITLE
Support for minetest 

### ISSUE THREAD

**Issue by tobyplowy** [Captain-Chaos/WorldPainter#52]
sorry for my bad English

Now that that's Out Of The Way I would like to Request compatibility for [minetest the free open source Minecraft like game](http://www.minetest.net) (now you probably think it's yet another stupid Minecraft clone but it isn't minetest has a big active Community and it's made by the community like this it also has a github page, but im getting off-topic here)

It would be amazing if this can work thanks for everyone's hard work to keep worldpainter up to date!
Minetest website http://www.minetest.net

**Comment by Captain-Chaos** [comment]
You're not the first to ask, and I am definitely interested in extending WorldPainter to other block based games. I can't find much information on the file format on disk that Minetest uses. Can you point me to any information about that?

**Comment by tobyplowy** [comment]
@Captain-Chaos No I can't but what you can do is ask on the forums?
https://forum.minetest.net

If you make a topic on there everyone will be trying to help you also thank you for your interest i preciate it (I may Give You A donation For Your Great work)

**Comment by tobyplowy** [comment]
@Captain-Chaos minetest is also open source so you can probably copy some mapgen code https://github.com/minetest/minetest

**Comment by tobyplowy** [comment]
@Captain-Chaos thank you!

**Comment by tobyplowy** [comment]
@Captain-Chaos when would this be implemented (I'm really looking forward to this!) Again thank you for your interest

**Comment by Captain-Chaos** [comment]
It's *way* too early to tell when, or even if... ;-)

Don't count on anything yet! I'm only looking into the feasibility for now.

**Comment by tobyplowy** [comment]
Ok

**Comment by tobyplowy** [comment]
@Captain-Chaos what do you think of minetest so far?

**Comment by Captain-Chaos** [comment]
It's pretty interesting. I like the comprehensive modding support, which Minecraft is sorely lacking.

**Comment by tobyplowy** [comment]
@Captain-Chaos yeah sadly it does

**Comment by tobyplowy** [comment]
@Captain-Chaos bdw your work is really appreciated!

I have already Made a ton Of Stuff!

**Comment by tobyplowy** [comment]
@Captain-Chaos how is progress going on mt support?

**Comment by Captain-Chaos** [comment]
It's going slowly, and about to go even more slowly since I'm about to leave for a three month vacation to the US. So don't expect much progress for the next few months!

**Comment by tobyplowy** [comment]
@Captain-Chaos are you having a nice vacation :)

**Comment by Captain-Chaos** [comment]
@tobyplowy Yes, very nice. I'm about to leave for Hawaii. Normal scheduled service will be resumed in July. :)

**Comment by tobyplowy** [comment]
@Captain-Chaos Cool thanks :)

**Comment by tobyplowy** [comment]
@Captain-Chaos the poeple on the forum make alot of nice maps with world painter thanks for the very early test build speaking of that when will you continue work on it this month?

**Comment by tobyplowy** [comment]
@Captain-Chaos Are you still interested in this?

**Comment by Captain-Chaos** [comment]
Yup. Sorry for the late response. This has lain dormant for a while due to me being very busy IRL, but now I've got some time again to work on it. It is not dead. ;-)

**Comment by tobyplowy** [comment]
@Captain-Chaos Well good, to bad that I lost interest in minetest 
(becouse the devs are not so opensource after all) instead I'm working on my own 
(well my friends are I'm just an artist) voxelsandbox game engine
If you are interested please come say hi you are more than welcome
https://discord.gg/QJdPcMb

Ook zou het tof zijn moest er een andere Nederlands spreker op de server komen :)
Ja ik spreek Nederlands wel Vlaams eigenlijk maar dat is het zelfde :)

**Comment by tobyplowy** [comment]
@Captain-Chaos Also if you have any way for me to contact you in private that wuld be amazing
I need to tell and ask you some tings

**Comment by Captain-Chaos** [comment]
There are various ways to private message me. You can message me on the Minecraft forum, where the official support thread lives: https://www.minecraftforum.net/members/Captain_Chaos. Or you can email me at worldpainter@pepsoft.org.

I would like to, but I'm afraid I don't have the time to drop into discord servers, sorry. Zelfs als ik er Nederlands kan spreken... ;-)

What is the voxelsandbox game you're working on? As long as the file format is stable and well documented I might be interested in supporting it.

**Comment by tobyplowy** [comment]
@Captain-Chaos i'm closing this becouse i have moved on to my own project and i no longer support minetest
also scarecrowman sent you an email with some more details about that project
