### ISSUE TITLE
GUI goes crazy

### ISSUE THREAD

**Issue by maxitanki** [Captain-Chaos/WorldPainter#55]
![image](https://cloud.githubusercontent.com/assets/26490142/24055859/04c06a40-0b42-11e7-860f-cad452449cdb.png)

this is what i see after i make a custom object layer or when i have been going in the program for a few minutes. i tried restarting and reinstalling but it keeps doing weird stuff. the only thing i didn't check was the java se runtime environment but i first want to know what the problem is. PLZZ help S.O.S.

**Comment by maxitanki** [comment]
and sometimes its even worse.

**Comment by Captain-Chaos** [comment]
This problem is described in the troubleshooting guide: http://www.worldpainter.net/trac/wiki/TroubleshootingWindows#Thescreenbecomescorrupted
