### ISSUE TITLE
[Feature] Scrollable Panels

### ISSUE THREAD

**Issue by randallbpotter15** [Captain-Chaos/WorldPainter#57]
I read one of the change logs where you mentioned custom layers may grow to be too big to fit and to think of organizing things in a different way to get around it.  I've been playing with a forked version of the code and it would seem creating a scrollable panel is within reach.

The default resolution on some laptops makes it really hard to interact with the map without scrolling panels and that hand/move tool I mentioned.  I'm currently maxed out at 1366x768 on my laptop. (I know it stinks)

**Comment by Captain-Chaos** [comment]
I did actually think of something though: you can create multiple palettes for custom layers, just right-click on a custom layer button to create a new palette, or move the layer to an existing one.

Regardless, I do agree it would still be handy if the panels were scrollable.

**Comment by Captain-Chaos** [comment]
I'm going to close this under the assumption that the multiple palettes cover your needs. Feel free to open a new issue if you still think something like this is needed!
