### ISSUE TITLE
[Feature] World heights higher than 256

### ISSUE THREAD

**Issue by frogocomics** [Captain-Chaos/WorldPainter#58]
I want there to be an option to allow worlds to have near unlimited heights.

- Imported heightmaps can be higher than 256
- When exporting, the map is exported in **slices of 256** (Basically multiple worlds)

**Comment by Captain-Chaos** [comment]
Interesting. Your first request is already possible. You can import height maps up to 65536 high. Currently you can only export those in MCRegion format though, as Anvil does not support non standard map heights.

What would be the point of the second request? You would end up with a bunch of separate maps, each containing only a cut off slice of the total map.

**Comment by frogocomics** [comment]
For the purpose of putting them together in a render. In the import heightmap dialog, the height is fixed, with certain options. Are you able to add in 4096? My request is basically to allow the world to export in slices.

**Comment by Captain-Chaos** [comment]
The height is fixed to what the height map contains. If you select a 16-bit, 65336 high height map, it will adjust the available options to include that.

I see. Hmm, I'm afraid that's too niche as a basis for such a complex feature. It would be a lot of work, for a result that isn't even playable and just has a cosmetic purpose. I'm afraid I'm going to reject this one, sorry!

Perhaps the existing possibilities of importing higher height maps than 256, and of being able to export them as Minecraft 1.1 (MCRegion) maps, already allows you to do what you need?

**Comment by frogocomics** [comment]
Does mcregion support new block types though?

**Comment by frogocomics** [comment]
If mcregion can support the new block types, is it viable for me to make a script to slice mcr worlds into a minecraft anvil world?

**Comment by frogocomics** [comment]
For example: magma block exports as -42 in mcr. Is that intended? Could you at least make it so that new blocks are supported in the mcr exports so I can slice them myself?

**Comment by Captain-Chaos** [comment]
Depends on what you mean by "new block types". MCRegion supports block ids up to 255, which includes all vanilla Minecraft blocks so far. It does not support extended block ids (between 256 and 4095).

As to whether it is viable for you to make such a script: I can't judge that, that depends on your programming skills. It would be complicated though.

**Comment by Captain-Chaos** [comment]
In regards to magma blocks: there are no negative numbers in MCRegion _or_ Anvil files. Make sure to interpret the numbers as unsigned, not signed.

**Comment by frogocomics** [comment]
Where is the code to export a Minecraft region file located? I need to better understand the file structure

**Comment by Captain-Chaos** [comment]
Try following the trail forwards and backwards from the ChunkImpl (for MCRegion) and ChunkImpl2 (for Anvil) classes; they are the classes that represent Minecraft chunks and contain the logic for loading, saving and accessing the data structures.

**Comment by frogocomics** [comment]
Where is the code for writing the physical file?

**Comment by Captain-Chaos** [comment]
The code for writing Minecraft maps to disk is all over the place, as WorldPainter is a large, complex and modular codebase. The actual physical writing of region files is in the RegionFile class. That doesn't contain any of the details of the actual contents of the chunks though.

**Comment by Captain-Chaos** [comment]
If you're wanting to actually write code which invokes WorldPainter to write Minecraft maps, looking into implementations of MinecraftWorld, such as JavaMinecraftWorld or CachingMinecraftWorld. Those classes will manage the region files for you and allow you to very easily export a minecraft map just by placing blocks.

**Comment by Captain-Chaos** [comment]
You may also want to look at JavaWorldExporter, which is the class which exports WorldPainter worlds as Minecraft maps. By the way, I'm currently refactoring the codebase so some of these names may be slightly different in the the public repo.
