### ISSUE TITLE
0xc0000005 ERROR

### ISSUE THREAD

**Issue by crimilo** [Captain-Chaos/WorldPainter#60]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbdf0bfd0c, pid=11372, tid=0x0000000000001f38
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [d3d9.dll+0xfd0c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x0000000019f40000):  JavaThread "AWT-Windows" daemon [_thread_in_native, id=7992, stack(0x000000001a8d0000,0x000000001a9d0000)]

siginfo: ExceptionCode=0xc0000005, writing address 0x0000000000000000

Registers:
RAX=0x0000000000000000, RBX=0x000000001a9cda90, RCX=0x00000000237c05a0, RDX=0x000000001a9ce2a0
RSP=0x000000001a9cd9e8, RBP=0x000000001a9cdd80, RSI=0x0000000000000001, RDI=0x0000000025125040
R8 =0x0000000000000000, R9 =0x0000000000000000, R10=0x00000000237c13bc, R11=0x0000000000000246
R12=0x0000000000000001, R13=0x000000001a9ce2a0, R14=0x0000000000000000, R15=0x0000000000000000
RIP=0x00007ffbdf0bfd0c, EFLAGS=0x0000000000010246

Top of Stack: (sp=0x000000001a9cd9e8)
0x000000001a9cd9e8:   00007ffbdf0c167f 000000001a9cda48
0x000000001a9cd9f8:   000000001a9cda50 00000000000005d8
0x000000001a9cda08:   0000000000010001 0000000000000000
0x000000001a9cda18:   0000000025125040 0000000000000000
0x000000001a9cda28:   00007ffbdf0d76a6 0000000000000000
0x000000001a9cda38:   0000000000000000 0000000000000001
0x000000001a9cda48:   0000000000000001 0000000000000000
0x000000001a9cda58:   0000000000000000 0000000000005c88
0x000000001a9cda68:   0000000000005c90 0000000000000000
0x000000001a9cda78:   000000001a9cdac8 0000000000000000
0x000000001a9cda88:   000000000000001a 0000000000000000
0x000000001a9cda98:   0000000000000000 00000000250d1560
0x000000001a9cdaa8:   00000000237c05a0 0000000000000000
0x000000001a9cdab8:   000000000114a3d8 0000000000000000
0x000000001a9cdac8:   0000000000000003 0000000000000000
0x000000001a9cdad8:   0000000000000000 0000000000000048 

Instructions: (pc=0x00007ffbdf0bfd0c)
0x00007ffbdf0bfcec:   e9 10 fe ff ff cc cc cc cc cc cc cc cc cc cc cc
0x00007ffbdf0bfcfc:   cc cc cc cc ff 25 00 00 00 00 30 96 c4 02 00 00
0x00007ffbdf0bfd0c:   00 00 5c 24 20 55 56 57 41 54 41 55 41 56 41 57
0x00007ffbdf0bfd1c:   48 8d 6c 24 c0 48 81 ec 40 01 00 00 48 8b 05 a9 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x000000001a9cda90 is pointing into the stack for thread: 0x0000000019f40000
RCX=0x00000000237c05a0 is an unknown value
RDX=0x000000001a9ce2a0 is pointing into the stack for thread: 0x0000000019f40000
RSP=0x000000001a9cd9e8 is pointing into the stack for thread: 0x0000000019f40000
RBP=0x000000001a9cdd80 is pointing into the stack for thread: 0x0000000019f40000
RSI=0x0000000000000001 is an unknown value
RDI=0x0000000025125040 is an unknown value
R8 =0x0000000000000000 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x00000000237c13bc is an unknown value
R11=0x0000000000000246 is an unknown value
R12=0x0000000000000001 is an unknown value
R13=0x000000001a9ce2a0 is pointing into the stack for thread: 0x0000000019f40000
R14=0x0000000000000000 is an unknown value
R15=0x0000000000000000 is an unknown value

Stack: [0x000000001a8d0000,0x000000001a9d0000],  sp=0x000000001a9cd9e8,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [d3d9.dll+0xfd0c]
C  [d3d9.dll+0x1167f]
C  [d3d9.dll+0x276a6]
C  [d3d9.dll+0x2cb68]
C  [d3d9.dll+0x2a81e]
C  [awt.dll+0x19e2d]
C  [awt.dll+0x19f8b]
C  [awt.dll+0x1a93f]
C  [awt.dll+0x1e4c5]
C  [awt.dll+0x1b609]
C  0x0000000003097f74

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.java2d.d3d.D3DGraphicsDevice.getDeviceCapsNative(I)I+0
j  sun.java2d.d3d.D3DGraphicsDevice.access$000(I)I+1
j  sun.java2d.d3d.D3DGraphicsDevice$1.run()V+8
v  ~StubRoutines::call_stub
j  sun.awt.windows.WToolkit.eventLoop()V+0
j  sun.awt.windows.WToolkit.run()V+58
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x0000000019f6c800 JavaThread "Image Fetcher 0" daemon [_thread_blocked, id=14028, stack(0x000000001ae70000,0x000000001af70000)]
  0x0000000019f43000 JavaThread "AWT-EventQueue-0" [_thread_in_native, id=14020, stack(0x000000001ab70000,0x000000001ac70000)]
=>0x0000000019f40000 JavaThread "AWT-Windows" daemon [_thread_in_native, id=7992, stack(0x000000001a8d0000,0x000000001a9d0000)]
  0x0000000019f3d800 JavaThread "AWT-Shutdown" [_thread_blocked, id=14140, stack(0x000000001a7d0000,0x000000001a8d0000)]
  0x0000000019ed6000 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=12816, stack(0x000000001a6d0000,0x000000001a7d0000)]
  0x00000000196e8800 JavaThread "Service Thread" daemon [_thread_blocked, id=10884, stack(0x0000000019ac0000,0x0000000019bc0000)]
  0x0000000017c57000 JavaThread "C1 CompilerThread2" daemon [_thread_blocked, id=11184, stack(0x00000000195c0000,0x00000000196c0000)]
  0x0000000017c4d000 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=11180, stack(0x00000000194c0000,0x00000000195c0000)]
  0x0000000017c49800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=13316, stack(0x00000000193c0000,0x00000000194c0000)]
  0x0000000017c55000 JavaThread "Attach Listener" daemon [_thread_blocked, id=10968, stack(0x00000000192c0000,0x00000000193c0000)]
  0x0000000017c53800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=11296, stack(0x00000000191c0000,0x00000000192c0000)]
  0x0000000017c3a800 JavaThread "Finalizer" daemon [_thread_blocked, id=11340, stack(0x0000000018eb0000,0x0000000018fb0000)]
  0x000000000306f000 JavaThread "Reference Handler" daemon [_thread_blocked, id=13320, stack(0x0000000018db0000,0x0000000018eb0000)]
  0x0000000002c0d800 JavaThread "main" [_thread_blocked, id=10952, stack(0x0000000000e20000,0x0000000000f20000)]

Other Threads:
  0x0000000017c18000 VMThread [stack: 0x0000000018cb0000,0x0000000018db0000] [id=10920]
  0x0000000019723800 WatcherThread [stack: 0x0000000019bc0000,0x0000000019cc0000] [id=10880]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 38400K, used 10792K [0x00000000d5800000, 0x00000000d8280000, 0x0000000100000000)
  eden space 33280K, 32% used [0x00000000d5800000,0x00000000d628a2f0,0x00000000d7880000)
  from space 5120K, 0% used [0x00000000d7d80000,0x00000000d7d80000,0x00000000d8280000)
  to   space 5120K, 0% used [0x00000000d7880000,0x00000000d7880000,0x00000000d7d80000)
 ParOldGen       total 87552K, used 0K [0x0000000080800000, 0x0000000085d80000, 0x00000000d5800000)
  object space 87552K, 0% used [0x0000000080800000,0x0000000080800000,0x0000000085d80000)
 Metaspace       used 10215K, capacity 10422K, committed 10624K, reserved 1058816K
  class space    used 1283K, capacity 1347K, committed 1408K, reserved 1048576K

Card table byte_map: [0x0000000012440000,0x0000000012840000] byte_map_base: 0x000000001203c000

Marking Bits: (ParMarkBitMap*) 0x00000000731fc720
 Begin Bits: [0x0000000012ef0000, 0x0000000014ed0000)
 End Bits:   [0x0000000014ed0000, 0x0000000016eb0000)

Polling page: 0x00000000010e0000

CodeCache: size=245760Kb used=2539Kb max_used=2539Kb free=243220Kb
 bounds [0x0000000003080000, 0x0000000003300000, 0x0000000012080000]
 total_blobs=991 nmethods=602 adapters=302
 compilation: enabled

Compilation events (10 events):
Event: 0.330 Thread 0x0000000017c57000  597       1       java.util.HashMap::afterNodeInsertion (1 bytes)
Event: 0.330 Thread 0x0000000017c57000 nmethod 597 0x00000000032f2e10 code [0x00000000032f2f60, 0x00000000032f3070]
Event: 0.330 Thread 0x0000000017c57000  598       3       java.util.StringTokenizer::scanToken (179 bytes)
Event: 0.331 Thread 0x0000000017c57000 nmethod 598 0x00000000032f4b90 code [0x00000000032f4e00, 0x00000000032f60f8]
Event: 0.331 Thread 0x0000000017c57000  599       3       sun.util.locale.LocaleUtils::isUpper (18 bytes)
Event: 0.331 Thread 0x0000000017c57000 nmethod 599 0x00000000032f6850 code [0x00000000032f69a0, 0x00000000032f6b70]
Event: 0.331 Thread 0x0000000017c57000  600       3       java.util.Objects::requireNonNull (15 bytes)
Event: 0.331 Thread 0x0000000017c57000 nmethod 600 0x00000000032f6bd0 code [0x00000000032f6d40, 0x00000000032f6f68]
Event: 0.332 Thread 0x0000000017c57000  601       3       java.util.HashMap::resize (359 bytes)
Event: 0.332 Thread 0x0000000017c57000 nmethod 601 0x00000000032f7050 code [0x00000000032f72a0, 0x00000000032f84c8]

GC Heap History (0 events):
No events

Deoptimization events (1 events):
Event: 0.160 Thread 0x0000000002c0d800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000000031e1974 method=com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.checkBeforeLoad(Lcom/sun/xml/internal/stream/Entity$ScannedEntity;II)I @ 18

Internal exceptions (10 events):
Event: 0.022 Thread 0x0000000002c0d800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x00000000d5807ca8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\
Event: 0.022 Thread 0x0000000002c0d800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x00000000d5807f90) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims
Event: 0.088 Thread 0x0000000002c0d800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d59d1510) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.088 Thread 0x0000000002c0d800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d59d1720) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.089 Thread 0x0000000002c0d800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d59d5ca8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.089 Thread 0x0000000002c0d800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d59d5eb8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.231 Thread 0x0000000002c0d800 Exception <a 'java/io/FileNotFoundException'> (0x00000000d5e17138) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.256 Thread 0x0000000002c0d800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x00000000d5ee3e70) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 0.257 Thread 0x0000000002c0d800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x00000000d5ef1530) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 0.336 Thread 0x0000000019f43000 Exception <a 'java/io/FileNotFoundException'> (0x00000000d6142d20) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp, line 709]

Events (10 events):
Event: 0.366 loading class sun/java2d/pipe/RenderQueue done
Event: 0.366 loading class sun/java2d/d3d/D3DRenderQueue done
Event: 0.366 loading class sun/java2d/pipe/RenderBuffer
Event: 0.366 loading class sun/java2d/pipe/RenderBuffer done
Event: 0.366 loading class sun/java2d/d3d/D3DRenderQueue$1
Event: 0.366 loading class sun/java2d/d3d/D3DRenderQueue$1 done
Event: 0.366 loading class sun/java2d/d3d/D3DGraphicsDevice$1Result
Event: 0.366 loading class sun/java2d/d3d/D3DGraphicsDevice$1Result done
Event: 0.366 loading class sun/java2d/d3d/D3DGraphicsDevice$1
Event: 0.366 loading class sun/java2d/d3d/D3DGraphicsDevice$1 done

Dynamic libraries:
0x00007ff68c860000 - 0x00007ff68c8cd000 	C:\Program Files\WorldPainter\uninstall.exe
0x00007ffc05bb0000 - 0x00007ffc05d8b000 	C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffc05760000 - 0x00007ffc0580e000 	C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffc02140000 - 0x00007ffc02389000 	C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffc05a50000 - 0x00007ffc05b9a000 	C:\WINDOWS\System32\USER32.dll
0x00007ffc02720000 - 0x00007ffc0273e000 	C:\WINDOWS\System32\win32u.dll
0x00007ffc051d0000 - 0x00007ffc051f7000 	C:\WINDOWS\System32\GDI32.dll
0x00007ffc02530000 - 0x00007ffc026b8000 	C:\WINDOWS\System32\gdi32full.dll
0x00007ffc02490000 - 0x00007ffc0252a000 	C:\WINDOWS\System32\msvcp_win.dll
0x00007ffc02740000 - 0x00007ffc02836000 	C:\WINDOWS\System32\ucrtbase.dll
0x00007ffc034c0000 - 0x00007ffc03561000 	C:\WINDOWS\System32\ADVAPI32.dll
0x00007ffc05640000 - 0x00007ffc056dd000 	C:\WINDOWS\System32\msvcrt.dll
0x00007ffc036e0000 - 0x00007ffc03739000 	C:\WINDOWS\System32\sechost.dll
0x00007ffc04d70000 - 0x00007ffc04e95000 	C:\WINDOWS\System32\RPCRT4.dll
0x00007ffc04c80000 - 0x00007ffc04cad000 	C:\WINDOWS\System32\IMM32.DLL
0x00007ffbfa070000 - 0x00007ffbfa2d7000 	C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.0_none_108e4f62dfe5d999\comctl32.dll
0x00007ffc03110000 - 0x00007ffc03409000 	C:\WINDOWS\System32\combase.dll
0x00007ffc020d0000 - 0x00007ffc0213a000 	C:\WINDOWS\System32\bcryptPrimitives.dll
0x00000000729e0000 - 0x000000007327c000 	c:\program files (x86)\java\jre1.8.0_131\bin\server\jvm.dll
0x00007ffc056e0000 - 0x00007ffc056e8000 	C:\WINDOWS\System32\PSAPI.DLL
0x00007ffc003d0000 - 0x00007ffc003f3000 	C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ffbfd940000 - 0x00007ffbfd94a000 	C:\WINDOWS\SYSTEM32\VERSION.dll
0x00007ffbf14b0000 - 0x00007ffbf14b9000 	C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x00007ffc04ea0000 - 0x00007ffc04f0c000 	C:\WINDOWS\System32\WS2_32.dll
0x0000000073c40000 - 0x0000000073d12000 	C:\WINDOWS\SYSTEM32\MSVCR100.dll
0x00007ffc00110000 - 0x00007ffc0013b000 	C:\WINDOWS\SYSTEM32\WINMMBASE.dll
0x00007ffc02440000 - 0x00007ffc02489000 	C:\WINDOWS\System32\cfgmgr32.dll
0x00000000729d0000 - 0x00000000729df000 	c:\program files (x86)\java\jre1.8.0_131\bin\verify.dll
0x00000000729a0000 - 0x00000000729c9000 	c:\program files (x86)\java\jre1.8.0_131\bin\java.dll
0x0000000072980000 - 0x0000000072996000 	c:\program files (x86)\java\jre1.8.0_131\bin\zip.dll
0x00007ffc037c0000 - 0x00007ffc04bf7000 	C:\WINDOWS\System32\SHELL32.dll
0x00007ffc03410000 - 0x00007ffc034ba000 	C:\WINDOWS\System32\shcore.dll
0x00007ffc02840000 - 0x00007ffc02f32000 	C:\WINDOWS\System32\windows.storage.dll
0x00007ffc03570000 - 0x00007ffc035c1000 	C:\WINDOWS\System32\shlwapi.dll
0x00007ffc02060000 - 0x00007ffc02071000 	C:\WINDOWS\System32\kernel.appcore.dll
0x00007ffc02080000 - 0x00007ffc020cc000 	C:\WINDOWS\System32\powrprof.dll
0x00007ffc02040000 - 0x00007ffc02055000 	C:\WINDOWS\System32\profapi.dll
0x0000000180000000 - 0x000000018002e000 	C:\Program Files\WorldPainter\.install4j\i4jinst.dll
0x00007ffc05080000 - 0x00007ffc051c5000 	C:\WINDOWS\System32\ole32.dll
0x00007ffc04cb0000 - 0x00007ffc04d70000 	C:\WINDOWS\System32\OLEAUT32.dll
0x0000000072970000 - 0x000000007297d000 	C:\Program Files (x86)\Java\jre1.8.0_131\bin\management.dll
0x00000000727d0000 - 0x0000000072968000 	C:\Program Files (x86)\Java\jre1.8.0_131\bin\awt.dll
0x00007ffc005f0000 - 0x00007ffc0066e000 	C:\WINDOWS\SYSTEM32\apphelp.dll
0x00007ffc00840000 - 0x00007ffc008d5000 	C:\WINDOWS\system32\uxtheme.dll
0x00007ffc04f10000 - 0x00007ffc05076000 	C:\WINDOWS\System32\MSCTF.dll
0x0000000002c30000 - 0x0000000002c67000 	C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll
0x0000000073790000 - 0x0000000073833000 	C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9279_none_08e667efa83ba076\MSVCR90.dll
0x00007ffbff000000 - 0x00007ffbff02a000 	C:\WINDOWS\system32\dwmapi.dll
0x00007ffbdaad0000 - 0x00007ffbdabf1000 	C:\WINDOWS\system32\opengl32.dll
0x00007ffbdcd20000 - 0x00007ffbdcd4c000 	C:\WINDOWS\SYSTEM32\GLU32.dll
0x00007ffbdf0b0000 - 0x00007ffbdf239000 	C:\WINDOWS\system32\d3d9.dll
0x00007ffbfb5e0000 - 0x00007ffbfb6bf000 	C:\WINDOWS\System32\DriverStore\FileRepository\nv_ref_pubwu.inf_amd64_f9309145156afb40\nvldumdx.dll
0x00007ffc02f40000 - 0x00007ffc03109000 	C:\WINDOWS\System32\crypt32.dll
0x00007ffc02020000 - 0x00007ffc02031000 	C:\WINDOWS\System32\MSASN1.dll
0x00007ffc026c0000 - 0x00007ffc02716000 	C:\WINDOWS\System32\WINTRUST.DLL
0x00007ffc037a0000 - 0x00007ffc037bd000 	C:\WINDOWS\System32\imagehlp.dll
0x00007ffc01ad0000 - 0x00007ffc01ae7000 	C:\WINDOWS\SYSTEM32\CRYPTSP.dll
0x00007ffc01550000 - 0x00007ffc01584000 	C:\WINDOWS\system32\rsaenh.dll
0x00007ffc01be0000 - 0x00007ffc01c05000 	C:\WINDOWS\SYSTEM32\bcrypt.dll
0x00007ffc01af0000 - 0x00007ffc01afb000 	C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
0x00007ffbd8470000 - 0x00007ffbd9485000 	C:\WINDOWS\System32\DriverStore\FileRepository\nv_ref_pubwu.inf_amd64_f9309145156afb40\nvd3dumx.dll
0x00007ffbfab50000 - 0x00007ffbfad21000 	C:\WINDOWS\system32\nvspcap64.dll
0x00007ffc05200000 - 0x00007ffc0563b000 	C:\WINDOWS\System32\SETUPAPI.dll
0x00007ffbfaa70000 - 0x00007ffbfab47000 	C:\WINDOWS\SYSTEM32\WINHTTP.dll
0x00007ffbfed50000 - 0x00007ffbfed63000 	C:\WINDOWS\SYSTEM32\WTSAPI32.dll
0x00007ffbf7bc0000 - 0x00007ffbf7fe1000 	C:\WINDOWS\system32\nvapi64.dll
0x00007ffc00e90000 - 0x00007ffc00f34000 	C:\WINDOWS\SYSTEM32\dxgi.dll
0x00007ffc00b80000 - 0x00007ffc00ba8000 	C:\WINDOWS\SYSTEM32\DEVOBJ.dll
0x00007ffbfb4f0000 - 0x00007ffbfb5d9000 	C:\Program Files (x86)\NVIDIA Corporation\3D Vision\nvSCPAPI64.dll
0x00007ffbf4cf0000 - 0x00007ffbf4e99000 	C:\WINDOWS\SYSTEM32\dbghelp.dll

VM Arguments:
jvm_args: -Dexe4j.semaphoreName=Local\c:_program_files_worldpainter_uninstall.exe -Dexe4j.isInstall4j=true -Dexe4j.moduleName=C:\Program Files\WorldPainter\uninstall.exe -Dexe4j.tempDir= -Dexe4j.unextractedPosition=0 -Djava.library.path=C:\Program Files\WorldPainter\.\.install4j;C:\Program Files\WorldPainter\.\.install4j\user;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\PuTTY\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\WorldPainter;C:\Users\NZXT\AppData\Local\Microsoft\WindowsApps;c:\program files (x86)\java\jre1.8.0_131\bin -Dexe4j.consoleCodepage=cp0 
java_command: C:\Program Files\WorldPainter\uninstall.exe
java_class_path (initial): C:\Program Files\WorldPainter\.install4j\i4jruntime.jar
Launcher Type: generic

Environment Variables:
PATH=C:\Program Files\WorldPainter\.\.install4j;C:\Program Files\WorldPainter\.\.install4j\user;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\PuTTY\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\WorldPainter;C:\Users\NZXT\AppData\Local\Microsoft\WindowsApps;c:\program files (x86)\java\jre1.8.0_131\bin
USERNAME=NZXT
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 15063 (10.0.15063.296)

CPU:total 4 (initial active 4) (4 cores per cpu, 1 threads per core) family 6 model 94 stepping 3, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, 3dnowpref, lzcnt, tsc, tscinvbit, bmi1, bmi2, adx

Memory: 4k page, physical 8350792k(5087948k free), swap 9661512k(5320160k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.131-b11) for windows-amd64 JRE (1.8.0_131-b11), built on Mar 15 2017 01:23:53 by "java_re" with MS VC++ 10.0 (VS2010)

time: Tue Jun 27 12:40:20 2017
elapsed time: 0 seconds (0d 0h 0m 0s)

I CANNOT OPEN WORLDPAINTER...HOW CAN I FIX?

**Comment by Captain-Chaos** [comment]
Was this an incident, or can you reproduce it?

**Comment by crimilo** [comment]
I resolved it, caused by msi afterburner

**Comment by Captain-Chaos** [comment]
Glad to hear it! :)
