### ISSUE TITLE
Scripting world options

### ISSUE THREAD

**Issue by WolfieWaffle** [Captain-Chaos/WorldPainter#61]
I am trying to make a system that can automate creating worlds using the scripting function, but I need certain options set. Things such as the gamemode of the world, whether to allow Minecraft to populate the entire terrain, etc. I don't see any documentation on these features, or the ability to actually export a world file from the command line, are these things possible to do?

**Comment by Captain-Chaos** [comment]
Yes. The scripting documentation is currently very incomplete, but the main secret is that the objects in the `world` and `dimension` variables are full Java objects which give you full read/write access to all their data. `world` is of type [World2](https://www.worldpainter.net/javadoc/org/pepsoft/worldpainter/World2.html); `dimension` of type [Dimension](https://www.worldpainter.net/javadoc/org/pepsoft/worldpainter/Dimension.html); following the links to their Javadoc documentation.

There is some general documentation about the scripting framework here: https://www.worldpainter.net/trac/wiki/Scripting, which shows among other things how to export worlds from a script, obtain layers, height maps, etc.

Issues aren't really meant for technical support like this, so I'm closing this one, but feel free to contact me directly if you have additional questions, for example by private message on the support forum: https://www.worldpainter.net/support
