### ISSUE TITLE
Unsigned Plugins

### ISSUE THREAD

**Issue by dags-** [Captain-Chaos/WorldPainter#63]
Hi, I help out on a small modded project that relies rather heavily on WP, and it looks like it'd be possible to add some 'quality of life' improvements via the plugin system for the mods that we use.

I had a read through the discussion on #27 where you have described how you intend the plugin system to work for publicly distributed plugins. I was wondering if it'd be possible to allow the use of unsigned jars (a user preference or something?) for bespoke plugins that I could share internally with the guys that do the painting for us?

**Comment by Captain-Chaos** [comment]
Sorry for the late response. I hope this is still relevant to you.

I'd rather not do that, as it's a safety feature, which I don't want casual users to be able to override.

What kind of functionality do you want to add via plugins? Would it be generally useful? Perhaps it's time for me to put some effort into this and start signing plugins.

**Comment by dags-** [comment]
Ok no worries. 
I can't remember exactly what they needed, think I was planning on having the mod dump a bunch of properties for it's blocks that could then be loaded into WP via a plugin - make mod plants behave like vanilla plants instead of solid cubes, that sort of thing.

**Comment by Captain-Chaos** [comment]
Well when you want to pick that up again, let me know! For now I'll close this issue.
