### ISSUE TITLE
erro java

### ISSUE THREAD

**Issue by llronaldoll** [Captain-Chaos/WorldPainter#64]
An unexpected error has occurred.

Type: java.lang.NullPointerException
Message: null

Please help debug the problem by using the button below to email the details of this error to the creator of this program.

The program may now be in an unstable state. It is recommended to restart it as soon as possible

**Comment by Captain-Chaos** [comment]
Do you remember what caused this to happen? Was it an incident or can you reproduce it?

**Comment by Captain-Chaos** [comment]
I assume this is no longer relevant, so I'll close this issue. Feel free to open a new one if you still encounter errors.
