### ISSUE TITLE
Error message :(

### ISSUE THREAD

**Issue by DiscJockeyDragon** [Captain-Chaos/WorldPainter#66]
I just get this when I start the world painter setup... Anyone know a fix...?
![screenshot_28](https://user-images.githubusercontent.com/38771918/39338622-81c6f76c-4989-11e8-9c71-c33f316a9b7b.png)

**Comment by Captain-Chaos** [comment]
It means you don't have 64-bit Java installed. The text next to the download link where you downloaded WorldPainter explains where to get it.

**Comment by DiscJockeyDragon** [comment]
Thank you!
