### ISSUE TITLE
Help with scripting - how to generate world from JS?

### ISSUE THREAD

**Issue by RareScrap** [Captain-Chaos/WorldPainter#73]
Hello. I want to write a script that will generate a world for me from the azgaar's Fantasy-Map-Generator like this:
![fantasy_map_1534147150963](https://user-images.githubusercontent.com/7997602/44123018-eba85290-a058-11e8-9e99-d336f84bd818.png)

I have a few questions:
1) Where can I find the full reference documentation for scripting API?
2) How to order the program to generate the world at a specified point?

Thank you in advance!

**Comment by Captain-Chaos** [comment]
Issues are for reporting bugs or requesting features; not for support questions. That's what the subreddit is for. I'll close this and answer your question there.

**Comment by RareScrap** [comment]
@Captain-Chaos I can't create post on reddit because i get 500 error when publish post
