### ISSUE TITLE
(Alpha) Modded blocks not supported using custom block addresses. 

### ISSUE THREAD

**Issue by JohnnyMadhouse** [Captain-Chaos/WorldPainter#75]
As the title states, maps created in the alpha build offer the possibility of typing custom block addresses into this window: 

[https://imgur.com/a/ilIwarb](https://imgur.com/a/ilIwarb)

However, this option doesn't appear to work just yet, as evidenced by the block selection defaulting to dirt once this window is closed.

**Comment by Captain-Chaos** [comment]
To be honest I thought that was working already, so thanks for drawing my attention to it.

**Comment by Captain-Chaos** [comment]
This isn't strictly a bug; it just isn't finished yet. :-) I'll work on getting this finished.
