### ISSUE TITLE
WP crashes when any tool is selected

### ISSUE THREAD

**Issue by supertassu** [Captain-Chaos/WorldPainter#77]
When you choose any tool WP just hangs and crashes. Happends both on latest and snapshot.

hs_err_pid7096.log: https://pastebin.com/g0Wfc9ey

couldn't find other log files. if there are just let me know.

**Comment by Captain-Chaos** [comment]
Perhaps the driver for the tablet is installed and causing trouble. You might try uninstalling it to see if that helps.

Since it doesn't look like this is something I can fix from WorldPainter's side I'm going to close the issue, but please let me know if the problem returns!
