### ISSUE TITLE
error while exporing Isroom

### ISSUE THREAD

**Issue by stiderspace** [Captain-Chaos/WorldPainter#83]
i get this everytime i try to export my world

`java.lang.ArrayIndexOutOfBoundsException: -1
	at org.pepsoft.worldpainter.layers.exporters.WPObjectExporter.isRoom(WPObjectExporter.java:352)
	at org.pepsoft.worldpainter.layers.exporters.WPObjectExporter$WPObjectFixup.fixup(WPObjectExporter.java:482)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.performFixups(AbstractWorldExporter.java:938)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.performFixupsIfNecessary(AbstractWorldExporter.java:913)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$parallelExportRegions$0(AbstractWorldExporter.java:302)

WorldPainter version: 2.5.8.1-SNAPSHOT (20181118184120)

java.version: 1.8.0_191
java.vendor: Oracle Corporation
java.vm.version: 25.191-b12
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\stiderspace
user.dir: E:\Programs(x64)\WorldPainter [SNAPSHOT]
user.country: GB
user.language: en

Free memory: 5777131992 bytes
Total memory size: 12171870208 bytes
Max memory size: 28327804928 bytes

World name: SEASON 4 update 3
Seed: 4609230686275311479
Bounds: -68, -68 => 67, 67
Height: 256
Number of tiles: 13780
Layers in use: Coral, lavaskirit, Palmen, IJsjes, Pyraentree, Swamp, Dwarf2, ijsplateau, Mushrooms, Kelp, Struiken, spring, Tunnels, Berken, arch, Reuzen, NetherCavern, Toendra, Tropen laag, junglegang, Rivier, opposite tunnel, Lava, Bos hoog, desertmount, Frost, Lava, kelp forests, Pine, Jungle, paddo's, Taigabos, Savanne, Junglecent, spawntunnel, Icemount, icy, Deciduous, Tunnels, connected, Taiga, desert plants, Biome, Tunnelsrand, dwarf, ijsberg, Bos laag, Moeras, Seagrass, Rivendell, smal Tunnels, ijsplaat, oceaantunnel, jungle, Magic, platform, Tropen hoog, Tunnels, tunneldown, pickle patch, Nether, Cracks, Dark Oak, Dood bos, Meloen
Border: WATER @ 62
Sub surface material: STONE_MIX
Water height: 62

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]`

**Comment by Captain-Chaos** [comment]
Could you try again with the latest version of the snapshot to see if this was fixed in the mean time?

**Comment by Captain-Chaos** [comment]
Since you didn't get back to me I'm going to assume it was fixed. Feel free to file a new issue if you encounter this or any other problem again!
