### ISSUE TITLE
Incompatibility with very tall heightmaps even when using the Cubic Chunks plugin

### ISSUE THREAD

**Issue by FyreByrns** [Captain-Chaos/WorldPainter#89]
![image](https://user-images.githubusercontent.com/26910523/52916699-ac14b700-3297-11e9-9943-6ea57254dd76.png)
When attempting to import a 16 bit heightmap into a cubic chunks enabled world, I'm unable to change the max height of the world to reflect the max value in the heightmap. If I attempt it anyway, there's a popup with an illegal argument exception because maxHeight is smaller than the height I require.

When attempting to create a new world from a heightmap, I have no way to change the world type I am creating and thus it cuts off my heightmap at 255.

**Comment by FyreByrns** [comment]
Bump

**Comment by Captain-Chaos** [comment]
> Bump

Don't hold your breath. I'm working on Minecraft 1.13 support, and it might be some time before I get around to this.

**Comment by Captain-Chaos** [comment]
In the latest release of WorldPainter you can now select the map format on the height map import screen, and import height maps into worlds with any map format.
