### ISSUE TITLE
Chests in structures not visible & not working with datapacks

### ISSUE THREAD

**Issue by Morsmorse** [Captain-Chaos/WorldPainter#91]
I wanted to scatter structures with chests with a custom loot-table around my map.

The chests get pasted but they're invisible until you open them and they don't work with the loot-table.
I tried spawning a chest with that loot-table, that work so it's not a datapack/loot-table related issue.

![Invisible Chest](https://user-images.githubusercontent.com/31167754/53303496-1e266680-386b-11e9-913b-a619af60cdb7.png)

**Comment by Captain-Chaos** [comment]
Which version of WorldPainter is this? The production version, or the Minecraft 1.13 support alpha (and what map format are you creating)?

**Comment by Captain-Chaos** [comment]
The next release of the beta will have much improved support for tile entities from structures, as well as rotation and mirroring support for Minecraft 1.13 materials. Presumably it will also fix this issue.

**Comment by Captain-Chaos** [comment]
The new version of the beta is released. It won't auto-update, but you can download it from the links in the reddit post. Let me know if you still have trouble or find additional issues!
