### ISSUE TITLE
Height-map too large

### ISSUE THREAD

**Issue by G1R-Productions** [Captain-Chaos/WorldPainter#92]
When I import a new world via height map it fails and produces this error:
EDIT:
I tried on multiple versions of the snapshot, including the latest snapshot and the result is the same.

java.lang.IllegalArgumentException: width*height > Integer.MAX_VALUE!
	at javax.imageio.ImageReader.getDestination(null:-1)
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(null:-1)
	at com.sun.imageio.plugins.png.PNGImageReader.read(null:-1)
	at javax.imageio.ImageIO.read(null:-1)
	at javax.imageio.ImageIO.read(null:-1)

WorldPainter version: 2.5.8.2-SNAPSHOT (20181125185522)

java.version: 1.8.0_202
java.vendor: Oracle Corporation
java.vm.version: 25.202-b08
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\Ghaz
user.dir: H:\Minecraft\WorldPainter [SNAPSHOT]
user.country: US
user.language: en

Free memory: 552314664 bytes
Total memory size: 818413568 bytes
Max memory size: 28559015936 bytes

World name: Generated World
Seed: -800983275071642285
Bounds: -19, -19 => 19, 19
Height: 256
Number of tiles: 1521
Layers in use: 
Border: null @ 62
Sub surface material: STONE_MIX
Water height: 62

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]

**Comment by Captain-Chaos** [comment]
I saw you closed this yourself, but just in case you're still interested and you hadn't figured it out yet: Java doesn't support images with an area (width times height) that is larger than 2³¹-1 (2,147,483,647; the largest possible value for a signed 32-bit integer).

For a square image that means not more than 46,340 pixels per side (if one side is shorter then the other side can of course be longer).
