### ISSUE TITLE
Snapshot custom layer duplication broken

### ISSUE THREAD

**Issue by G1R-Productions** [Captain-Chaos/WorldPainter#95]
On the latest snapshot when you right click a custom layer and select duplicate the new duplicate layer does not contain any of the objects from the original layer which you selected to duplicate.

**Comment by Captain-Chaos** [comment]
Thanks for bringing it to my attention. This has actually never worked, but I do agree it would be much more useful, so I fixed it. It will be in the next release of the beta.

**Comment by Captain-Chaos** [comment]
The new version of the beta is released. It won't auto-update, but you can download it from the links in the reddit post. Let me know if you still have trouble or find additional issues!
